### ISSUE TITLE
opperwezen beat 5 times SF-zh version 2016-12-09 

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#173] opened 2016-12-13 19:48 UTC
https://fr.lichess.org/LVefUdC5
https://fr.lichess.org/qBsQuseR/black
https://fr.lichess.org/HFJ0y6P6
https://fr.lichess.org/3EsZ0bVd/black
https://fr.lichess.org/uG2YXuwR

I already saw an interesting position from 2nd game : 28.Kg1?? selfmate even after depth 7.
https://fr.lichess.org/qBsQuseR/black#54

**Comment by Vinvin20** [comment] 2016-12-19 10:37
opperwezen beating SF from a very bad eval (-6.4) : https://fr.lichess.org/tXAdPPEZ#39

**Comment by ddugovic** [comment] 2017-01-02 01:23
Duplicate of #172.

**Closed by ddugovic** 2017-01-02 01:23 UTC
