### ISSUE TITLE
Another atomic crash

### ISSUE THREAD

**Issue by benwh1** [ddugovic/Stockfish#437] opened 2017-11-04 09:15 UTC
```
position fen r3kb1r/p3p2p/4bnp1/1p6/3p4/1P1PP3/P1P2PPP/RNB1KB1R w KQkq - 1 9
...
info depth 36 seldepth 57 multipv 1 score cp 313 lowerbound nodes 6240839590 nps 770762 hashfull 999 tbhits 0 time 8096970 pv g2g4
sf_debug: position.cpp:1237: void Position::do_move(Move, StateInfo&, bool): Assertion `to == st->epSquare' failed.
Aborted (core dumped)
```

Looks like a problem with en-passant captures.

**Comment by benwh1** [comment] 2017-11-04 21:41
Actually, it turns out that this position didn't crash without debugging enabled. But I do have another segfault from a different position, but it unfortunately takes a long time to reach (>7 hours). I'll try to run it with debugging enabled soon.

**Comment by ddugovic** [comment] 2017-11-05 16:25
Oops, I suspect that this is the cause:
https://github.com/ddugovic/Stockfish/commit/9be478e17193fa60e31213c4aae3685b5bbf39f1#diff-760a56b9dcfc15bf67577d7d6a273fb9R1142

**Comment by ddugovic** [comment] 2017-11-05 17:09
I think this is a duplicate of #434 .

**Closed by ddugovic** 2017-11-05 17:09 UTC
