### ISSUE TITLE
Check extension in 3-checks

### ISSUE THREAD

**Issue by Vinvin20** [ddugovic/Stockfish#281] opened 2017-03-16 09:17 UTC
Idea to improve the search in 3-checks (I don't know the current status of extensions) : 
- Extend search by 2 plies when a king is in check that's the first check for this side.
- Extend search by 4 plies when a king is in check that's the second check for this side.

**Comment by ddugovic** [comment] 2017-03-16 09:53
The current status of extensions may be found in https://github.com/ddugovic/Stockfish/blob/master/src/search.cpp .

**Comment by ianfab** [comment] 2017-03-16 11:11
I think that extending by more than two ply might be too dangerous with regard to search explosions, but check extensions in three-check chess definitely are very important, e.g. see this successful test: http://35.161.250.236:6543/tests/view/5894d31e6e23db014ac09f68. I think it is a good idea that we should consider the current number of checks to determine the search extension.

**Comment by ddugovic** [comment] 2017-03-16 13:01
I agree and am confused that I don't remember a PR for that change as it looks quite good and simple.

**Comment by ianfab** [comment] 2017-03-16 13:17
As far as I can see there has not been any LTC test for it. So we could maybe rebase and run an LTC test.

**Comment by Vinvin20** [comment] 2017-03-16 14:55
> I think that extending by more than two ply might be too dangerous with regard to search explosions

As 3 checks ends the game, the explosion is very limited.

**Comment by Vinvin20** [comment] 2017-03-16 15:57
One thing that can be done is : extend 2 plies but the first ply is a null move et the second is a search only for checking moves. That will only fail for zugzwang positions (very rare in 3 checks).

**Comment by ddugovic** [comment] 2017-03-16 23:04
@Vinvin20 Could you please try coding these suggestions since other people are busy contributing code which works?

**Comment by ianfab** [comment] 2017-03-17 12:02
The [LTC test](http://35.161.250.236:6543/tests/view/58cad89f6e23db7956a14388) of theo's patch failed.

**Comment by Vinvin20** [comment] 2017-03-20 22:13
> The LTC test of theo's patch failed.

Thanks for the test ! But bad results :-(

**Comment by ddugovic** [comment] 2017-03-24 23:43
Upstream is changing check extension logic, so I'll wait until that's merged to try anything...

**Comment by ddugovic** [comment] 2017-04-01 14:15
I intend to attempt a [simplification](http://35.161.250.236:6543/tests/view/58dfb5d06e23db2fa8080eb5) first.

**Comment by ianfab** [comment] 2017-04-01 15:02
With the large number of tuned parameters I would not consider this a simplification, but it looks like this will pass regardless of the choice of bounds. I am a bit surprised that tuning so many parameters at the same time worked that well.

**Comment by ddugovic** [comment] 2017-04-01 17:28
@ianfab Given #278 I am interested in [simplifications](http://github.com/ddugovic/Stockfish/compare/bfb232e...130abaf#diff-760a56b9dcfc15bf67577d7d6a273fb9) even should minor variant regressions occur due to accidental fucntional changes.  We haven't fully tuned everything yet so the test result does not surprise me.

The test indicates that at most a minor regression is possible (though I agree, I'm inclined to assume any bounds would have worked).

**Comment by ianfab** [comment] 2017-04-01 18:35
@ddugovic The other conditions after `is_three_check()` will not be executed in any variant other than three-check chess, so I think the simplification does not increase nps. The bug is already fixed, so in my opinion the only reason to change this code fragment in `see_ge` is to decrease complexity in order make it easier to find improvements in the future. So if a change like https://github.com/ddugovic/Stockfish/commit/0a021732d35fe7774fca6c97155442a321ce793d passes a simplification test, I think it would be reasonable to commit it. Otherwise I do not see (yet) why it should be changed.

For changes that aim at improving speed for standard chess while allowing small regressions for variants, we should define criteria for the trade-off. I do not think it is a good idea to allow regressions without ensuring to get a certain speed-up in return, or to test patches as simplifications if the simplification is only a negligible part of the change. Of course there is no sharp distinction between simplifications and other changes, but since we use pretty loose bounds for simplifications, there should be a good reason when using these bounds.

If you are referring to [this test](http://35.161.250.236:6543/tests/view/58dfb5d06e23db2fa8080eb5), the only thing I can see is that the parameter tweaks seem to result in a big Elo gain.

**Comment by ddugovic** [comment] 2017-04-01 19:48
@ianfab I believe because we are using Link-Time Optimization and `-O3`, there are greater opportunities for optimization when code is reduced (for example, 0a021732d35fe7774fca6c97155442a321ce793d makes it *possible* for `if (is_three_check() && color_of(moved_piece(m)) == sideToMove && gives_check(m)) return true` to be inlined into calling contexts where `color_of(moved_piece(m)) == sideToMove` is provably satisfied, thereby removing this branch from other contexts).  Hopefully in the future I can learn better use of template functions etc. so the compiler may optimize better prior to Link-Time Optimization.

I apologize for my earlier use of "simplification" when I meant "reduction" (due to a non-equivalency).  In terms of strength I too am most concerned about popular variants:

[Blitz](https://en.lichess.org/stat/rating/distribution/blitz): **80,496 players**
[Crazyhouse](https://en.lichess.org/stat/rating/distribution/crazyhouse): 3,446 players
Antichess: 2,526 players(!)
Atomic: 1,757 players
Others: < 1,200 players

Fair enough, I guess we shouldn't encourage handling all code reductions as simplifications.  Going forward I'll have to be more careful not to introduce bugs...

I suppose since variable tuning is non-negligible, in the future I'll submit reductions+tuning under normal bounds (not simplification bounds).

**Comment by ddugovic** [comment] 2017-04-16 13:31
I eventually got around to submitting a simple test:
http://35.161.250.236:6543/tests/view/58f371226e23db2fa8081095

**Comment by ddugovic** [comment] 2017-04-20 19:44
I recommend that this issue is an XY problem: the current algorithm is fine and repeated attempts to change it have lost Elo.

**Comment by ianfab** [comment] 2017-04-20 19:57
Considering that something like half of the open issues are ideas for improvements without really raising an issue, we should maybe collect these in the opening post of a "suggestions and ideas" thread.

**Comment by ddugovic** [comment] 2017-04-20 20:20
I do not object, although collecting ideas on GitHub instead of in a public forum not only distracts developers trying to find a particular issue, but also challenges us from recruiting new developers:

In addition to the [Lichess Feedback](http://en.lichess.org/forum/lichess-feedback) forum, I joined the Lichess team [Coders](http://en.lichess.org/team/coders) as well as [Crazyhouse Engine Development and Game Analyses](http://en.lichess.org/team/crazyhouse-engine-development-and-game-analyses).

During the 1st CVCA Crazyhouse Championship I was active on [TalkChess](http://talkchess.com/).

**Comment by ddugovic** [comment] 2017-04-24 12:12
I have moved this issue to [Stockfish XY Problems](http://en.lichess.org/forum/team-coders/stockfish-xy-problems).

**Closed by ddugovic** 2017-04-24 12:12 UTC
