### ISSUE TITLE
EGTB not working for eligible variants

### ISSUE THREAD

**Issue by Nordlandia** [ddugovic/Stockfish#471] opened 2017-12-05 14:14 UTC
In variant _twokings_ probing syzygy does not work even if both sides extra king is removed from the board.  Once both spare kings has vanished from the board, the variant is back to normal FIDE chess. 

Doesn't it make sense to probe syzygy if PV results in classic FIDE position without extra kings?

**Comment by ddugovic** [comment] 2017-12-05 18:49
I wonder how strong SF *twokings* is in comparison to other engines & whether the code would be much simpler (and handle all single-king positions properly) were it a subvariant (of normal chess).

**Comment by Nordlandia** [comment] 2017-12-05 18:51
Syzygy add endgame strength. One way is to activate syzygy once one king on each side is captured. I dunno how much work this require.

**Comment by ianfab** [comment] 2017-12-05 21:00
@ddugovic Since Two Kings is not that different from standard chess, I think that the few improvements to piece values and king danger evaluation might have already been sufficient to make it stronger than other engines.

I thought about making it a subvariant of normal chess when I implemented it, but I thought that we would not gain much (only removing some array entries that might in some cases even be useful to optimize), but introducing a non-zero piece value for the king in standard chess would be ugly, and workarounds also do not seem more elegant either.

The contempt change is no functional change for default contempt 0, so I do not see how it is related to twokings or how it affects playing strength. There are some merge conflicts, but the removal of `DrawValue` should simplify the variant code, e.g., regarding the stalemate evaluation code.

@Nordlandia The gain from tablebases usually is not that much (maybe 10-20 Elo), but it would of course be a nice feature. From a first look at the code, it seems to require a couple of changes, but it would not add much additional logic, so it is not very problematic regarding code maintenance.

**Comment by Nordlandia** [comment] 2017-12-05 21:18
@ianfab supporting syzygy is mainly intended for engine matches.  

**Candidates**

1. Prove syzygy during all times. This mean SF can consult egtb (syzygy assistance) even if 3 or 4 kings is present on board. 
2.  Probe syzygy only once FIDE position is present on board.

**Comment by ianfab** [comment] 2017-12-05 21:51
@Nordlandia The king values (same for royal and non-royal) for middlegame and endgame resulted from [SPSA tuning](http://35.161.250.236:6543/tests/view/5a00e9546e23db2fc44adbd8) and can be found in [types.h](https://github.com/ddugovic/Stockfish/blob/7904686e54ca7292ad68fcc7403f0e3f702e410c/src/types.h#L428). It is a bit less than a knight.

Regarding syzygy, I currently only consider the second option as feasible. Adapting the syzygy generation and probing code requires far more work (and at least I am anyway not very familiar with that code).

**Comment by Nordlandia** [comment] 2017-12-05 22:56
According wikipedia article the king suprasses the knight in the endgame, so i 780 might not be the best EG value. Perhaps 800-825 is more suitable. 

Better ask HGM.

**Comment by ianfab** [comment] 2017-12-05 23:11
@Nordlandia In my experience, tuning usually finds better values than the ones estimated by humans, so human input is more useful for finding new evaluation terms than for optimizing their values. The optimal values can also differ between engines, so human estimates are mostly useful to find a reasonable starting value, afterwards automated tuning can take over. Please also note that the effective piece value for the king might be a bit higher than the raw piece value itself, because the piece-square table bonuses are quite high for the king.

**Comment by Nordlandia** [comment] 2017-12-05 23:23
You're right. 

But in this case SF is assessing the position wrong being up a piece + extra king is worth than +3 evaluation. Real evaluation is more like 4 - 4.5 point ahead. 

![tk](https://user-images.githubusercontent.com/26534454/33636201-82932086-da1b-11e7-972b-a19e0c6cafe7.png)

**Comment by ianfab** [comment] 2017-12-06 08:04
@Nordlandia The value of the king anyway only plays a role if there is a difference in the number of kings (since it otherwise cancels out), and a difference can only be in the situation of 2 vs. 1 kings if you are not playing with more than two kings. So the values should already be optimized for that case (and for SEE).

**Comment by HGMuller** [comment] 2017-12-06 10:44
@Nordlandia: I don't see why you would think humans would evaluate that position as 4+. I certainly would not do that, and despite everything I do consider myself human. In fact +3 seems already optimistic. This is an opening position, and a genuine Commoner usually performs already worse then a Knight there. Surely the fact that the second King would turn absolutely royal on part of the board would suppress its value even further.

**Comment by Nordlandia** [comment] 2017-12-06 13:28
@HGMuller: in the opening the Commoner is inferior to the knight, that's true. What about the endgame, doesn't the Commoner excel in the endgame opposed to the opening?

Isn't SF slightly overoptimistic here?

![tk2](https://user-images.githubusercontent.com/26534454/33663772-95071d50-da91-11e7-9ae3-77db7dbf68df.png)

**Comment by HGMuller** [comment] 2017-12-06 16:10
Why ask me, rather than trying it yourself by playing out that position a couple of hundred times. If Stockfish does not randomize enough you can give it a book with 20x20 start positions where one of the Pawns of each side is advanced one step. Then you would know who has the advantage here.

I have only tested this with Fairy-Max, and Fairy-Max is not really smart w.r.t. mating potential (it thinks KNK = +3). So I cannot trust the results are 100% accurate.

**Comment by ddugovic** [comment] 2017-12-06 19:53
@Nordlandia Maybe start with [SPSA](https://github.com/ianfab/spsa) and https://github.com/ddugovic/Stockfish/tree/tune_variant if you're unsure what parameter value(s) you wish to submit to a test.

**Comment by Nordlandia** [comment] 2017-12-06 20:28
If you're satisfied with current piece values then everything is fine. 

I can launch 100 game match à la 3+2 time control in KK vs KN position and see which side is superior.

**Comment by ianfab** [comment] 2017-12-06 21:17
@Nordlandia Feel free to change the king value and submit tests on fishtest (let me know if you need help). Ideas for improvements are very welcome, and I do not have any preference for a certain value except for the one that turns out to give the best performance Elo-wise. In my experience it is best to simply do tests and let the results decide to avoid overthinking ideas, because whether a certain idea or value works well in an engine also often changes over time as other changes are applied.

**Comment by Nordlandia** [comment] 2017-12-06 22:13
The problem is that i have never submitted idea for test before.  What do i need to do?

**Comment by ianfab** [comment] 2017-12-06 22:36
@Nordlandia There is some documentation in the wiki regarding the three steps [setting up the repository](https://github.com/ddugovic/Stockfish/wiki/Creating-my-first-test#initial-setup), [creating the branches for testing](https://github.com/ddugovic/Stockfish/wiki/Creating-my-first-test#create-your-test) and [submitting a test](https://github.com/ddugovic/Stockfish/wiki/Creating-my-first-test#run-your-test). I do not know your experience with git, coding, or the fishtest test submission page, so let me know if there is a certain area where you need more detailed explanation.

You do not need to be hesitant when using the test submission page if you are not familiar with it. Worst case something will be inconsistent, then I will not approve the test and it can be deleted (and maybe resubmitted).

**Comment by Nordlandia** [comment] 2017-12-07 09:15
KK vs KN scored 13 wins and rest drawn games at 2+2 à la 100 games at 1-core. 

![kk](https://user-images.githubusercontent.com/26534454/33707360-6d4777f0-db37-11e7-9371-fbff9df354f4.png)

**Comment by ddugovic** [comment] 2017-12-07 13:44
Maybe `KnightValueEgTwoKings` is wrong.  I've submitted an [SPSA parameter tuning session](http://35.161.250.236:6543/tests/view/5a29459d6e23db35f28baf7e) using parameters specified by running `./stockfish`:

```
$ ./stockfish 
Stockfish 071217 64 BMI2 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
PieceValue[TWOKINGS_VARIANT][MG][1],171,0,342,17.1,0.0020
PieceValue[TWOKINGS_VARIANT][MG][2],764,0,1528,76.4,0.0020
PieceValue[TWOKINGS_VARIANT][MG][3],826,0,1652,82.6,0.0020
PieceValue[TWOKINGS_VARIANT][MG][4],1282,0,2564,128.2,0.0020
PieceValue[TWOKINGS_VARIANT][MG][5],2526,0,5052,252.6,0.0020
PieceValue[TWOKINGS_VARIANT][MG][6],526,0,1052,52.6,0.0020
PieceValue[TWOKINGS_VARIANT][EG][1],240,0,480,24,0.0020
PieceValue[TWOKINGS_VARIANT][EG][2],848,0,1696,84.8,0.0020
PieceValue[TWOKINGS_VARIANT][EG][3],891,0,1782,89.1,0.0020
PieceValue[TWOKINGS_VARIANT][EG][4],1373,0,2746,137.3,0.0020
PieceValue[TWOKINGS_VARIANT][EG][5],2646,0,5292,264.6,0.0020
PieceValue[TWOKINGS_VARIANT][EG][6],780,0,1560,78,0.0020
```

**Comment by HGMuller** [comment] 2017-12-07 14:43
@Nordlandia: Are you sure the games are independent enough, when you start them all from the same position? If Stockfish Variant does not randomize, it could be that you are basically playing the same game all the time (which ends in a draw), and that only occasionally another move is done at some point (because Stockfish happens to change move very close to a timeout that would force it to play a move), leading to two other games with low probability, one ending in a win, the other in a loss.

When you say 13 wins. was it always the KK side that won? The result reports 7 wins and 6 losses. Is this just because you were alternating colors? Results are easier to interpret when you don't alternate colors. Or, when you cannot disable such alternation, alternate the starting position, so that even games are played with a pair of black Kings, ad odd games with a pair of white Kings.

**Comment by Nordlandia** [comment] 2017-12-07 14:58
@HGMuller i had to abort 3+2 match because of repetition. All games were drawn.

Also i requested CuteChess to implement _lock engine as white_ in engine matches. 

https://github.com/cutechess/cutechess/issues/321

**Comment by HGMuller** [comment] 2017-12-07 15:08
Late end-games tend to be drawish, (if nearly equal), not much can be done about that. But to prevent repetition. you can start every game from a different position.

**Comment by Nordlandia** [comment] 2017-12-07 15:45
I have to use EPDfor thar right?

**Comment by HGMuller** [comment] 2017-12-07 15:55
I don't know. I never used cute-chess. I don't know how you specify the start position now. With XBoard the start FEN would have to be in a file, and you can have 100 FENs in that file just as easily as you can have one.

**Comment by ddugovic** [comment] 2017-12-07 22:27
SPSA/SF suggest the commoner is overvalued!
![commoner](https://user-images.githubusercontent.com/1834123/33741801-73a439ec-db6b-11e7-8e2d-02ae82aa3b24.png)

**Comment by Nordlandia** [comment] 2017-12-08 18:55
@ddugovic: my testing advocates the opposite. KK vs KN is not worse.

**Comment by ddugovic** [comment] 2017-12-08 19:16
@Nordlandia I don't disagree; I'm just saying the commoner seems overvalued.  I'll try some testing from `8/8/8/3n4/4k3/8/8/K6K w - -` later (maybe even increasing the 50-move-rule parameter to 100; I think there's a parameter for that?)

**Comment by Nordlandia** [comment] 2017-12-08 19:32
Interesting position, clearly only KK can win.

**Comment by ddugovic** [comment] 2017-12-08 20:11
Good point.  I'll need to use `-draw movecount=100` and `-tbpieces 2` (running locally):
https://github.com/cutechess/cutechess/blob/master/projects/cli/res/doc/help.txt

**Comment by ddugovic** [comment] 2017-12-09 11:19
OK, once I fixed cutechess I observed (tc=240/0.1+1):

```
[Event "?"]
[Site "?"]
[Date "2017.12.09"]
[Round "1"]
[White "Stockfish 091217 64 BMI2"]
[Black "Stockfish 091217 64 BMI2"]
[Result "1/2-1/2"]
[FEN "8/8/8/3n4/4k3/8/8/K6K w - - 0 1"]
[SetUp "1"]

1. Kb2 Ne3 2. Kc3 Nd5+ 3. Kb3 Nb6 4. Kg1 Kd3 5. Kb4 Kd4 6. Kb5 Nc4 7. Kc6 Ne5+
8. Kd6 Nf7+ 9. Kc7 Kc5 10. Kf2 Ne5 11. Ke2 Kd5 12. Kd2 Nc4 13. Kc3 Na3 14. Kb3
Nb5 15. Kd7 Kc5 16. Kb2 Nd6 17. Ke6 Nb5 18. Ke7 Kb4 19. Kc1 Kc4 20. Kb2 Na7
21. Ke6 Nb5 22. Ke5 Kd3 23. Kf4 Nd6 24. Kg4 Nc4+ 25. Kb3 Ne5 26. Kf4 Nc4 27. Kg4
Nb6 28. Kg3 Nd5 29. Kb2 Ne3 30. Kf4 Nd1+ 31. Ka3 Nc3 32. Kg5 Nd1 33. Kf6 Kc4
34. Ka2 Kc3 35. Ke7 Nb2 36. Ke6 Nd1 37. Ke7 Nb2 38. Ke6 Nd1 39. Kd6 Nb2 40. Kd5
Nd1 41. Kc5 Nf2 42. Kb1 Nh3 43. Kd5 Kb4 44. Ke4 Ng5 45. Kf5 Nh7 46. Kc2 Nf8
47. Kd3 Nd7 48. Kde4 Nc5+ 49. Kd5 Nd3 50. Kde4 Nc1 1/2-1/2
```

Then in cutechess I changed the 50-move rule to a 100-move rule, and in Stockfish disabled the 50-move rule, producing (tc=240/0.1+1):

```
[Event "?"]
[Site "?"]
[Date "2017.12.09"]
[Round "1"]
[White "Stockfish 091217 64 BMI2"]
[Black "Stockfish 091217 64 BMI2"]
[Result "1/2-1/2"]
[FEN "8/8/8/3n4/4k3/8/8/K6K w - - 0 1"]
[SetUp "1"]

1. Kb2 Ne3 2. Kc3 Kd5 3. Kd3 Nc4 4. Kg2 Ne5+ 5. Kc3 Nf7 6. Kf2 Ne5 7. Ke3 Nc6
8. Ked3 Kc5 9. Kc4+ Kd6 10. Kb5 Ne7 11. Kcc4 Ke6 12. Kbc5 Ke5 13. K5d4+ Kf6
14. Ke4 Ke6 15. Kb5 Ng6 16. Ke3 Kd5 17. Kb4 Ne7 18. Kd3 Nf5 19. Kc4+ Ke6 20. Kd3
Kd5 21. Kc4+ Ke6 22. Kbc3 Ne3 23. Kc5 Nd5+ 24. Kd2 Ke5 25. Ke2 Ke4 26. Kd2 Nf4
27. Kc3 Ne6 28. K5c4 Ke5 29. K3d3 Kf5 30. Kc2 Ke4 31. K2d3+ Kf5 32. Kc2 Ke4
33. K2c3 Ke5 34. K3b4 Nd4 35. Kbc5 Nf5 36. K4d5+ Kf6 37. Kdc6 Ke5 38. Kb4 Ne7
39. Kd7 Nd5+ 40. Kb5 Nf6 41. Kdc6 Ne4 42. Kc4 Nd2+ 43. Kd3 Nb3 44. Kc3 Nc1
45. Kd2 Nb3 46. Kc3 Nd4 47. Kc5 Nf5 48. K5c4 Nd6 49. Kd4+ Kf6 50. Kd5 Nf5
51. Kc5 Ne3 52. Kd6 Nf5 53. Kd7 Ke5 54. Kc4 Ne3+ 55. Kb4 Nd1 56. Kc4 Kf4 57. Kd4
Ne3 58. Kc7 Kf3 59. Kc6 Nd1 60. Kd7 Kg3 61. Ke6 Kf4 62. Kc5 Ke3 63. Kf5 Ke2
64. Kd4 Kd2 65. Kde5 Nc3 66. Kd4 Nd1 67. Kde5 Nc3 68. Kef4 Kc2 69. Ke3 Na4
70. Kd4 Nc3 71. Kfe5 Kd2 72. Kf6 Kc2 73. Kfe5 Kd2 74. Kf6 Kc2 75. Kf5 Kd2
76. Kc4 Nd1 77. Kd4 Nf2 78. Kfe5 Ke2 79. Kf4 Nd1 80. Kfe4 Kd2 81. Kf5 Nc3
82. Kfe5 Ne2+ 83. Kd5 Nc1 84. Kc4 Nd3 85. Kd6 Nf2 86. Kdc5 Ke2 87. K5d4 Ke1
88. Kcd5 Kd2 89. K5c5 Ke1 90. Ke3 Nd1 91. Kf4 Kd2 92. Ke5 Nc3 93. Kb4 Ne2
94. Kc5 Kd3 95. Kb4 Kd2 96. Kb5 Kc3 97. Kc5 Ng3 98. Kf4 Ne2 99. Ke3 Ng3
100. Kd4+ Kd2 1/2-1/2
```

So then I added a specialized endgame function, changed `Position::non_pawn_material()` to include the commoner, and produced:

```
[Event "?"]
[Site "?"]
[Date "2017.12.09"]
[Round "1"]
[White "Stockfish 091217 64 BMI2"]
[Black "Stockfish 091217 64 BMI2"]
[Result "1/2-1/2"]
[FEN "8/8/8/3n4/4k3/8/8/K6K w - - 0 1"]
[SetUp "1"]

1. Kb2 Ke5 2. Kb3 Kd4 3. Kg1 Nc7 4. Kf2 Nb5 5. Ke2 Nc3 6. Kf3 Nd5 7. Kg4 Nc3
8. Kh5 Nd1 9. Kh6 Nc3 10. Kg5 Nb1 11. Kh5 Nd2+ 12. Kb4 Nb1 13. Kh6 Nd2 14. Kg7
Nb1 15. Kg8 Nc3 16. Kg7 Nb1 17. Kg6 Nd2 18. Kh5 Nb1 19. Kh6 Nd2 20. Kg6 Nb1
21. Kh7 Nd2 22. Kg6 Nb1 23. Kh7 Nd2 24. Kg8 Nb1 25. Kf8 Nd2 26. Kg8 Nb1 27. Kf7
Nd2 28. Ke6 Nc4 29. Kf7 Nb2 30. Kg7 Nd1 31. Kf6 Nb2 32. Kb5 Nc4 33. Kg6 Nb2
34. Kh7 Nd1 35. Kc6 Nb2 36. Kb5 Nd1 37. Kb6 Ne3 38. Kh6 Ke4 39. Kc5 Nd1 40. Kd6
Nb2 41. Kc6 Kd4 42. Kg7 Nc4 43. Kf6 Ne5+ 44. Kb5 Kd5 45. Kg5 Nd3 46. Kh5 Nc1
47. Kh6 Na2 48. Ka4 Kc4 49. Ka3 Nc1 50. Kh7 Kc5 51. Kb2 Ne2 52. Kb3 Nc1+ 53. Kc2
Na2 54. Kb2 Nb4 55. Kc3 Na2+ 56. Kb2 Nb4 57. Ka3 Nd5 58. Kg6 Kd4 59. Kb2 Nc3
60. Kf7 Kd3 61. Kc1 Na2+ 62. Kb2 Nb4 63. Ka3 Nd5 64. Kb2 Ne3 65. Kf6 Nd1+
66. Kc1 Ne3 67. Ke5 Nc4 68. Kd5 Kc3 69. Kb1 Ne3 70. Ke4 Nd1 71. Kd5 Ne3 72. Ke4
Nd1 73. Ka2 Kc4 74. Ka3 Nf2 75. Ke3 Nd1 76. Ke2 Nc3 77. Ke3 Nb1+ 78. Ka2 Nc3+
79. Ka3 Nb1+ 80. Kb2 Nc3 81. Kd2 Na4+ 82. Kc2 Nc5 83. Ke1 Nb3 84. Kf2 Na1+
85. Kb2 Nb3 86. Ke2 Nc5 87. Kd2 Nd3+ 88. Ka3 Nb4 89. Kc1 Nd3 90. Kb1 Kc3
91. Kba2 Kc4 92. K2b3+ Kd5 93. Kc2 Nc5 94. Kb4 Ne4 95. Kd1 Nd6 96. Kc1 Nc4
97. Kc2 Nd6 98. Kb2 Nc4+ 99. Ka2 Nd2 100. Kb5 Ne4 1/2-1/2
```

**Comment by ddugovic** [comment] 2017-12-09 11:57
A bit more experimentation progressed no further; maybe there isn't a forced mate?

```
[Event "?"]
[Site "?"]
[Date "2017.12.09"]
[Round "1"]
[White "Stockfish 091217 64 BMI2"]
[Black "Stockfish 091217 64 BMI2"]
[Result "1/2-1/2"]
[FEN "8/8/8/3n4/4k3/8/8/K6K w - - 0 1"]
[PlyCount "200"]
[SetUp "1"]
[TimeControl "240/0.1+0.1"]
[Variant "twokings"]

1. Kb2 {+0.63/3 0s} Ke5 {-0.63/4 0s} 2. Kg2 {+0.71/7 0.005s}
Ke4 {-0.71/9 0.014s} 3. Kb3 {+0.75/8 0.008s} Ne3 {-0.71/8 0.003s}
4. Kf2 {+0.75/9 0.007s} Ng4 {-0.75/11 0.021s} 5. Ke2 {+0.75/10 0.008s}
Ne5 {-0.75/8 0.005s} 6. Kc3 {+0.80/8 0.009s} Nf3 {-0.75/10 0.008s}
7. Kd3+ {+0.80/10 0.014s} Kf4 {-0.80/11 0.017s} 8. Kdc4 {+0.80/11 0.019s}
Ne1 {-0.80/12 0.013s} 9. K4d4 {+0.80/13 0.028s} Nf3 {-0.80/16 0.066s}
10. Kd5 {+0.80/14 0.009s} Ke3 {-0.80/16 0.015s} 11. Kdc4 {+0.80/15 0.015s}
Kf4 {-0.80/19 0.019s} 12. K4d3 {+0.80/16 0.019s} Ne5 {-0.80/19 0.016s}
13. Kd4 {+0.75/18 0.036s} Nf3 {-0.75/19 0.024s} 14. Kd5 {+0.75/19 0.026s}
Ke3 {-0.75/16 0.023s} 15. Kdc4 {+0.75/18 0.042s} Kf4 {-0.75/19 0.025s}
16. Kc5 {+0.84/18 0.052s} Ke4 {-0.75/20 0.028s} 17. K3c4 {+0.84/19 0.025s}
Ke3 {-0.75/19 0.040s} 18. K4d5 {+0.75/19 0.049s} Kd3 {-0.84/15 0.039s}
19. Kcd6 {+0.75/20 0.026s} Ke3 {-0.80/19 0.047s} 20. K6e6 {+0.75/21 0.025s}
Kf4 {-0.80/19 0.073s} 21. Kc4 {+0.75/22 0.060s} Ke3 {-0.80/21 0.042s}
22. Kcd5 {+0.75/23 0.021s} Kf4 {-0.80/21 0.019s} 23. Kc5 {+0.75/25 0.058s}
Ke4 {-0.80/24 0.057s} 24. Kd5+ {+0.75/21 0.026s} Kd3 {-0.80/23 0.018s}
25. Ke6 {+0.75/23 0.026s} Ng5 {-0.75/18 0.029s} 26. Kf5 {+0.75/20 0.028s}
Ne4+ {-0.71/19 0.051s} 27. Kd5 {+0.75/22 0.029s} Nc3+ {-0.71/18 0.029s}
28. Ke5 {+0.75/21 0.20s} Ne4 {-0.71/23 0.037s} 29. Kff4 {+0.75/23 0.023s}
Nc3 {-0.71/22 0.031s} 30. Kff5 {+0.75/24 0.025s} Ne4 {-0.71/26 0.037s}
31. Kff4 {+0.75/26 0.038s} Nc3 {-0.71/26 0.033s} 32. Kd6 {+0.71/19 0.035s}
Kd4 {-0.71/19 0.039s} 33. Ke5+ {+0.71/19 0.055s} Kd3 {-0.71/23 0.025s}
34. Kf4 {+0.71/23 0.037s} Ne4+ {-0.71/20 0.026s} 35. Kd5 {+0.67/18 0.035s}
Nc3+ {-0.71/22 0.026s} 36. Ke6 {+0.67/17 0.035s} Ne4 {-0.71/22 0.023s}
37. Kfe5 {+0.67/19 0.026s} Nc3 {-0.71/25 0.035s} 38. Kf7 {+0.67/18 0.023s}
Ne2 {-0.71/22 0.023s} 39. Kg7 {+0.67/17 0.036s} Nc3 {-0.71/26 0.050s}
40. Kg6 {+0.67/18 0.025s} Ne4 {-0.71/25 0.014s} 41. Kf7 {+0.67/21 0.071s}
Nc3 {-0.71/27 0.048s} 42. Kg8 {+0.67/23 0.042s} Nb1 {-0.71/29 0.046s}
43. Kf7 {+0.67/24 0.043s} Nc3 {-0.71/29 0.046s} 44. Kg8 {+0.67/25 0.056s}
Nb1 {-0.71/23 0.045s} 45. Kh8 {+0.67/23 0.050s} Nd2 {-0.71/25 0.046s}
46. Kg7 {+0.67/25 0.046s} Ne4 {-0.71/27 0.053s} 47. Kh8 {+0.67/27 0.044s}
Nd2 {-0.71/29 0.050s} 48. Kh7 {+0.67/22 0.057s} Ne4 {-0.71/27 0.049s}
49. Kg6 {+0.67/24 0.052s} Nd2 {-0.71/29 0.060s} 50. Kd5 {+0.75/22 0.051s}
Ne4 {-0.71/29 0.052s} 51. Kf5 {+0.67/23 0.064s} Nc3+ {-0.71/28 0.064s}
52. Ke6 {+0.67/22 0.062s} Ne4 {-0.71/27 0.056s} 53. Kee5 {+0.67/24 0.047s}
Nc3 {-0.71/29 0.058s} 54. Kg6 {+0.67/23 0.051s} Ne4 {-0.71/33 0.068s}
55. Kh7 {+0.67/28 0.067s} Nd2 {-0.71/29 0.050s} 56. Kg7 {+0.67/28 0.11s}
Nc4+ {-0.71/27 0.055s} 57. Kf4 {+0.71/22 0.13s} Nd6 {-0.71/25 0.058s}
58. Kg6 {+0.71/23 0.046s} Ne4 {-0.71/28 0.056s} 59. Kf3 {+0.71/23 0.048s}
Nd2+ {-0.71/23 0.052s} 60. Kf4 {+0.71/25 0.058s} Ne4 {-0.71/32 0.059s}
61. Kf3 {+0.71/28 0.077s} Nd2+ {-0.71/29 0.061s} 62. Kf2 {+0.71/30 0.057s}
Ne4+ {-0.71/28 0.074s} 63. Ke1 {+0.71/30 0.053s} Nd6 {-0.71/29 0.054s}
64. Kd1 {+0.71/28 0.054s} Ne4 {-0.71/24 0.062s} 65. Kc1 {+0.71/29 0.060s}
Kd4 {-0.71/25 0.054s} 66. Kc2 {+0.71/26 0.055s} Nd6 {-0.71/27 0.062s}
67. Kd2 {+0.71/30 0.060s} Ne4+ {-0.71/29 0.062s} 68. Ke2 {+0.71/33 0.063s}
Nc3+ {-0.71/31 0.055s} 69. Kf3 {+0.71/29 0.062s} Kd3 {-0.71/33 0.074s}
70. Kg5 {+0.71/28 0.059s} Ne4 {-0.71/27 0.083s} 71. Kgg4 {+0.71/30 0.072s}
Nd2+ {-0.71/32 0.062s} 72. Kf4 {+0.71/29 0.064s} Ne4 {-0.71/35 0.067s}
73. Kff3 {+0.71/32 0.067s} Nd2+ {-0.71/37 0.067s} 74. Kf4 {+0.71/33 0.059s}
Ne4 {-0.71/37 0.058s} 75. Ke5 {+0.71/31 0.063s} Nd2 {-0.71/32 0.069s}
76. Kef5 {+0.71/30 0.063s} Ne4 {-0.71/35 0.067s} 77. Kf3 {+0.71/33 0.075s}
Nd2+ {-0.71/36 0.071s} 78. Kf2 {+0.71/33 0.062s} Nc4 {-0.71/28 0.068s}
79. Ke1 {+0.71/28 0.081s} Ne3 {-0.71/30 0.070s} 80. Kg6 {+0.71/28 0.057s}
Nc4 {-0.71/27 0.060s} 81. Kd1 {+0.71/31 0.061s} Nd2 {-0.71/30 0.065s}
82. Kf5 {+0.71/30 0.061s} Nb1 {-0.71/26 0.077s} 83. Kc1 {+0.71/30 0.069s}
Nd2 {-0.71/31 0.34s} 84. Kg6 {+0.71/32 0.059s} Ne4 {-0.71/31 0.063s}
85. Kb1 {+0.71/27 0.058s} Nd2+ {-0.71/28 0.059s} 86. Ka1 {+0.64/29 0.93s}
Ke3 {-0.71/25 0.058s} 87. Kf5 {+0.71/21 0.13s} Kd4 {-0.71/26 0.92s}
88. Kb2 {+0.71/22 0.034s} Nc4+ {-0.71/18 0.050s} 89. Kc1 {+0.71/23 0.78s}
Ne3 {-0.71/22 0.77s} 90. Kf4 {+0.71/20 0.058s} Ng2 {-0.63/18 0.17s}
91. Kg3 {+0.69/19 0.66s} Ne3 {-0.63/17 0.11s} 92. Kf3 {+0.08/16 0.33s}
Nc4 {-0.08/16 0.49s} 93. Kd1 {0.00/14 0.061s} Ne5 {0.00/16 0.13s}
94. Kfe2 {0.00/20 0.088s} Kd5 {0.00/28 0.11s} 95. Kdd2 {0.00/18 0.024s}
Kd6 {0.00/31 0.11s} 96. Kc3 {0.00/22 0.035s} Nc6 {0.00/32 0.036s}
97. Kd1 {0.00/26 0.040s} Ne5 {0.00/27 0.040s} 98. Kb3 {0.00/31 0.039s}
Nc6 {0.00/35 0.039s} 99. Kc1 {0.00/46 0.037s} Nd4+ {0.00/56 0.039s}
100. Kbb2 {0.00/67 0.040s} Nc2 {0.00/127 0.003s, Draw by hundred moves rule}
1/2-1/2
```

**Comment by Nordlandia** [comment] 2017-12-09 12:11
I'm not saying commoner is stronger than knight. What i'm saying based on my testing is that commoner is on par knights value in endgame.  Knight EG value: 838 Commoner: 800 !?

**Comment by HGMuller** [comment] 2017-12-09 15:06
Note that Nordlandia tested KK vs KN in the presense of many Pawns. KCKN with a normal Commoner is know to be a general draw from end-game tables, (and the part-time royalty is unlikely to make any difference), but so is KRKN. So this doesn't tell you a lot about the value. End-games without Pawns are always very drawish. They are also very rare. Usually each side still has 3 or 4 Pawns, by the time you get down to a single piece each. So how the piece does without Pawns hardly affects the piece value.

**Comment by ianfab** [comment] 2017-12-09 15:50
The slightly negative evaluation in the position with pawns is actually not caused by the piece values (including the piece-square tables), but by the quadratic material imbalance bonuses, see below. Adding the king to the material imbalance arrays (as for antichess and horde chess) and tuning those values might be worth a try.

```
setoption name UCI_Variant value twokings
position fen 1n2k3/pppppppp/8/8/8/8/PPPPPPPP/3KK3 w - - 0 1
d
eval
info string variant twokings startpos rnbqkknr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKKNR w KQkq - 0 1

 +---+---+---+---+---+---+---+---+
 |   | n |   |   | k |   |   |   |
 +---+---+---+---+---+---+---+---+
 | p | p | p | p | p | p | p | p |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 | P | P | P | P | P | P | P | P |
 +---+---+---+---+---+---+---+---+
 |   |   |   | K | K |   |   |   |
 +---+---+---+---+---+---+---+---+

Fen: 1n2k3/pppppppp/8/8/8/8/PPPPPPPP/3KK3 w - - 0 1
Key: 3DF2870F8AC0B7D6
Checkers: 
      Eval term |    White    |    Black    |    Total    
                |   MG    EG  |   MG    EG  |   MG    EG  
----------------+-------------+-------------+-------------
       Material |   ---   --- |   ---   --- |  0.14  0.31 
      Imbalance |   ---   --- |   ---   --- | -0.66 -0.66 
          Pawns |   ---   --- |   ---   --- |  0.00  0.00 
        Knights |  0.00  0.00 |  0.03 -0.06 | -0.03  0.06 
        Bishops |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
          Rooks |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
         Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
       Mobility |  0.00  0.00 | -0.04 -0.12 |  0.04  0.12 
    King safety |  1.03 -0.07 |  1.03 -0.07 |  0.00  0.00 
        Threats |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
   Passed pawns |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
          Space |  0.00  0.00 |  0.00  0.00 |  0.00  0.00 
     Initiative |   ---   --- |   ---   --- |  0.00 -0.10 
----------------+-------------+-------------+-------------
          Total |   ---   --- |   ---   --- | -0.51 -0.27 

Total Evaluation: -0.19 (white side)
```

**Comment by ddugovic** [comment] 2017-12-09 18:55
I might have found a bug with the Two Kings game phase calculation, among other things: https://github.com/ddugovic/Stockfish/commit/e7caa7a3a2700379007314355181c5b585abc934

**Comment by Nordlandia** [comment] 2017-12-10 08:51
Do you know  what the bug does?

**Comment by ddugovic** [comment] 2017-12-10 13:55
The bug causes:
* game phase calculation does not consider commoner(s)
* endgame scaling factor does not consider commoner(s)
* king safety/threat does not consider commoner(s)
* space evaluation does not consider commoner(s)
* endgame tablebase probe does not consider commoner(s)
* razoring, futility pruning, and shallow depth pruning do not consider commoner(s)

**Comment by Nordlandia** [comment] 2017-12-10 14:09
* endgame tablebase probe does not consider commoner(s)

Comment: that's fine if EGTB is not eligible before both commoners is captured and removed from the board, as mentioned earlier in this thread.

**Comment by ddugovic** [comment] 2017-12-10 14:12
Sure, but this thread doesn't define what is an "eligible variant".  It's true that Two Kings tablebases haven't yet been compiled, but if antichess tablebases can exist then I see no reason why Two Kings tablebases couldn't also exist.

**Comment by Nordlandia** [comment] 2017-12-10 14:25
5-men two kings syzygy is indeed possible. The question is whether Ronald De Man is interested in generate them.

**Comment by ddugovic** [comment] 2018-02-24 15:06
Perhaps once https://github.com/syzygy1/Rustfish matures I'll fork it and address this issue in Rust...

**Closed** 2018-04-07 14:24 UTC
