### ISSUE TITLE
Atomic: draw misjudgement in this position

### ISSUE THREAD

**Issue by ProgramFOX** [ddugovic/Stockfish#545] opened 2018-11-14 22:23 UTC
https://lichess.org/hyzAtJHm/black#36

Stockfish suggests 19. Rdg1 with an evaluation of `0`. But after playing that move, it finds that Bg7 is #-10. I'd suspect depth 46 would be enough to not evaluate the position as a draw. Either I'm wrong in that, or there's an eval bug somewhere.

**Comment by ianfab** [comment] 2018-11-14 23:42
The evaluation of the position as a draw seems to be correct, but only 19. Rdf1 secures the draw. Stockfish prefers Rf1 already from depth 10 and does not switch later, so the bug does not seem to be easily reproducible. However, there are quite big fluctuations ins the selective depth, which is most likely caused by the many three-fold repetition variations due to perpetual checks. So depth 46 in this position does not necessarily correspond to a very deep search, since the selective search depth is low.

Repeating the search with multipv=2 shows that it takes Stockfish some time to find that Rdg1 is losing, so it could be that for a short search it goes for the wrong move, since it apparently at first believes that black anyway has to go for the perpetual.

--------
**multipv = 1**
```
setoption name UCI_Variant value atomic
position fen 2r2bk1/pp5p/6p1/8/3P1P2/PPP1P3/6PP/1nKR3R w - - 1 19
go depth 48
```
```
info string variant atomic startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
info depth 1 seldepth 1 multipv 1 score cp 567 nodes 20 nps 10000 tbhits 0 time 2 pv c3c4
info depth 2 seldepth 2 multipv 1 score cp 594 nodes 43 nps 21500 tbhits 0 time 2 pv c3c4 a7a6
info depth 3 seldepth 3 multipv 1 score cp 617 nodes 76 nps 38000 tbhits 0 time 2 pv c3c4 a7a6 c4c5
info depth 4 seldepth 5 multipv 1 score cp 519 nodes 288 nps 144000 tbhits 0 time 2 pv e3e4 a7a5 c3c4 a5a4
info depth 5 seldepth 5 multipv 1 score cp 668 nodes 406 nps 203000 tbhits 0 time 2 pv e3e4
info depth 6 seldepth 6 multipv 1 score cp 527 nodes 939 nps 313000 tbhits 0 time 3 pv e3e4 a7a5 g2g4 a5a4 e4e5 a4b3
info depth 7 seldepth 7 multipv 1 score cp 553 nodes 2089 nps 417800 tbhits 0 time 5 pv c3c4 b1c3 d1f1 c3e4 g2g4
info depth 8 seldepth 9 multipv 1 score cp 487 nodes 6761 nps 676100 tbhits 0 time 10 pv e3e4 b7b5 d1e1 b1d2 e4e5 g8f7 e1e3
info depth 9 seldepth 12 multipv 1 score cp 0 nodes 19751 nps 705392 tbhits 0 time 28 pv d1f1 b1c3 c1d1 c8c2 e3e4 c2c1 d1d2 c1c2
info depth 10 seldepth 15 multipv 1 score cp 0 nodes 21784 nps 726133 tbhits 0 time 30 pv d1f1 b1c3 c1d1 c8c2 f1f3 c2c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2
info depth 11 seldepth 15 multipv 1 score cp 0 nodes 23619 nps 715727 tbhits 0 time 33 pv d1f1 b1c3 c1d1 c8c2 f1f3 c2c1 d1d2 c1d1 d2c2 d1d2 c2c1 d2d1 c1c2
info depth 12 seldepth 13 multipv 1 score cp 0 nodes 25902 nps 719500 tbhits 0 time 36 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2c1
info depth 13 seldepth 13 multipv 1 score cp 0 nodes 28586 nps 752263 tbhits 0 time 38 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 14 seldepth 12 multipv 1 score cp 0 nodes 32811 nps 781214 tbhits 0 time 42 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 15 seldepth 13 multipv 1 score cp 0 nodes 36437 nps 792108 tbhits 0 time 46 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 16 seldepth 23 multipv 1 score cp 0 nodes 42813 nps 839470 tbhits 0 time 51 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2c1
info depth 17 seldepth 22 multipv 1 score cp 0 nodes 56894 nps 862030 tbhits 0 time 66 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2b2 e3e4 b2c2 c1d1 c2d2 d1c1
info depth 18 seldepth 20 multipv 1 score cp 0 nodes 65761 nps 876813 tbhits 0 time 75 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2b2 e3e4 b2c2 c1d1 c2d2 d1c1
info depth 19 seldepth 20 multipv 1 score cp 0 nodes 78333 nps 910848 tbhits 0 time 86 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2b2 e3e4 b2c2 c1d1 c2d2 d1c1 d2c2
info depth 20 seldepth 23 multipv 1 score cp 0 nodes 97497 nps 902750 tbhits 0 time 108 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2b2 e3e4 b2c2 c1d1 c2d2 d1c1 d2d1 c1c2 d1c1 c2d2 c1d1
info depth 21 seldepth 20 multipv 1 score cp 0 nodes 127090 nps 948432 tbhits 0 time 134 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 22 seldepth 32 multipv 1 score cp 0 nodes 158108 nps 1007057 tbhits 0 time 157 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2b2 e3e4 b2b1 c1d2 b1d1 d2c2 d1c1 c2d2 c1c2 d2d1 c2d2 d1c1 d2d1
info depth 23 seldepth 12 multipv 1 score cp 0 nodes 190689 nps 1071286 tbhits 0 time 178 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 24 seldepth 13 multipv 1 score cp 0 nodes 220526 nps 1108170 tbhits 0 time 199 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 25 seldepth 12 multipv 1 score cp 0 nodes 263860 nps 1188558 tbhits 0 time 222 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 26 seldepth 13 multipv 1 score cp 0 nodes 341785 nps 1261199 tbhits 0 time 271 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1d2
info depth 27 seldepth 34 multipv 1 score cp 0 nodes 423767 nps 1242718 tbhits 0 time 341 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 c2d2 b1b2 d2c1 b2d2 e3e4 d2c2 c1d1 c2c1 d1d2 c1c2
info depth 28 seldepth 23 multipv 1 score cp 0 nodes 522320 nps 1273951 tbhits 0 time 410 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 c2d2 b1b2 d2c1 b2d2 e3e4 d2c2 c1d1 c2c1 d1d2 c1c2
info depth 29 seldepth 22 multipv 1 score cp 0 nodes 668026 nps 1352279 tbhits 0 time 494 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 30 seldepth 17 multipv 1 score cp 0 nodes 805039 nps 1371446 tbhits 0 time 587 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 c2d2 b1b2 d2c1 b2b1
info depth 31 seldepth 16 multipv 1 score cp 0 nodes 1022945 nps 1331959 tbhits 0 time 768 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 32 seldepth 13 multipv 1 score cp 0 nodes 1320759 nps 1360204 tbhits 0 time 971 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 33 seldepth 12 multipv 1 score cp 0 nodes 1629923 nps 1433529 hashfull 441 tbhits 0 time 1137 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 34 seldepth 13 multipv 1 score cp 0 nodes 2107276 nps 1519304 hashfull 553 tbhits 0 time 1387 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 35 seldepth 13 multipv 1 score cp 0 nodes 2460309 nps 1516836 hashfull 616 tbhits 0 time 1622 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 36 seldepth 12 multipv 1 score cp 0 nodes 2903578 nps 1529003 hashfull 678 tbhits 0 time 1899 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 37 seldepth 13 multipv 1 score cp 0 nodes 3502677 nps 1514998 hashfull 770 tbhits 0 time 2312 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 38 seldepth 12 multipv 1 score cp 0 nodes 4187020 nps 1468099 hashfull 835 tbhits 0 time 2852 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 39 seldepth 12 multipv 1 score cp 0 nodes 4925312 nps 1449900 hashfull 895 tbhits 0 time 3397 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 40 seldepth 12 multipv 1 score cp 0 nodes 5829913 nps 1472572 hashfull 927 tbhits 0 time 3959 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 41 seldepth 12 multipv 1 score cp 0 nodes 7268251 nps 1496140 hashfull 965 tbhits 0 time 4858 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 42 seldepth 12 multipv 1 score cp 0 nodes 8989131 nps 1522291 hashfull 981 tbhits 0 time 5905 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 43 seldepth 13 multipv 1 score cp 0 nodes 11080679 nps 1549095 hashfull 996 tbhits 0 time 7153 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1c1
info depth 44 seldepth 12 multipv 1 score cp 0 nodes 14736925 nps 1589743 hashfull 997 tbhits 0 time 9270 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 45 seldepth 77 multipv 1 score cp 0 nodes 17243485 nps 1564034 hashfull 999 tbhits 0 time 11025 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 c2d2 b1c1 e3e4 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 b3b4 b1c1 c2d2 c1c2 d2d1 c2e2 f4f5 e2e1 d1d2 e1d1 d2c2 d1c1 c2d2 c1c2 d2e1 c2f2 f1g1 f2e2 e1d1 e2d2 d1c1 d2c2 c1b1 c2c1 b1b2 c1b1 b2c2 b1b2 c2d1
info depth 46 seldepth 19 multipv 1 score cp 0 nodes 21887569 nps 1581586 hashfull 999 tbhits 0 time 13839 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 c2d2 b1c1 e3e4 c1c2 d2d1 c2c1
info depth 47 seldepth 19 multipv 1 score cp 0 nodes 24808278 nps 1559876 hashfull 999 tbhits 0 time 15904 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 c2d2 b1c1 e3e4 c1d1 d2c2 d1c1
info depth 48 seldepth 19 multipv 1 score cp 0 nodes 28820017 nps 1537231 hashfull 999 tbhits 0 time 18748 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 c2d2 b1c1 e3e4 c1d1 d2c2 d1c1
bestmove d1f1 ponder b1c3
```
--------
**multipv = 2**
```
setoption name multipv value 2
setoption name UCI_Variant value atomic
position fen 2r2bk1/pp5p/6p1/8/3P1P2/PPP1P3/6PP/1nKR3R w - - 1 19
go depth 30
```
```
info string variant atomic startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
info depth 1 seldepth 1 multipv 1 score cp 567 nodes 39 nps 19500 tbhits 0 time 2 pv c3c4
info depth 1 seldepth 1 multipv 2 score cp 423 nodes 39 nps 19500 tbhits 0 time 2 pv f4f5
info depth 2 seldepth 2 multipv 1 score cp 594 nodes 114 nps 57000 tbhits 0 time 2 pv c3c4 a7a6
info depth 2 seldepth 2 multipv 2 score cp 439 nodes 114 nps 57000 tbhits 0 time 2 pv e3e4 a7a6
info depth 3 seldepth 3 multipv 1 score cp 674 nodes 193 nps 96500 tbhits 0 time 2 pv c3c4 a7a6 f4f5
info depth 3 seldepth 3 multipv 2 score cp 659 nodes 193 nps 96500 tbhits 0 time 2 pv e3e4 a7a6 c3c4
info depth 4 seldepth 4 multipv 1 score cp 525 nodes 425 nps 212500 tbhits 0 time 2 pv e3e4 f8e7 c3c4 b1c3
info depth 4 seldepth 4 multipv 2 score cp 488 nodes 425 nps 212500 tbhits 0 time 2 pv c3c4 b1c3 d1f1 c3e4
info depth 5 seldepth 5 multipv 1 score cp 452 nodes 1100 nps 366666 tbhits 0 time 3 pv c3c4 b1c3 d1f1 c3e4 f1f3
info depth 5 seldepth 5 multipv 2 score cp 428 nodes 1100 nps 366666 tbhits 0 time 3 pv f4f5 b1d2 c3c4 d2f1 e3e4 f1h2
info depth 6 seldepth 6 multipv 1 score cp 585 nodes 1702 nps 425500 tbhits 0 time 4 pv e3e4 b1d2 c3c4
info depth 6 seldepth 6 multipv 2 score cp 488 nodes 1702 nps 425500 tbhits 0 time 4 pv c3c4 b1c3 d1f1 c3e4 f1f3
info depth 7 seldepth 7 multipv 1 score cp 554 nodes 5886 nps 588600 tbhits 0 time 10 pv c3c4 b1c3 d1f1 c3e4 g2g4 e4d2 f1f2
info depth 7 seldepth 8 multipv 2 score cp 401 nodes 5886 nps 588600 tbhits 0 time 10 pv h2h4 b7b5 h1h3 g8f7 e3e4 b1d2
info depth 8 seldepth 11 multipv 1 score cp 476 nodes 16917 nps 676680 tbhits 0 time 25 pv g2g4 b7b5 e3e4 b1d2 e4e5 d2f3
info depth 8 seldepth 10 multipv 2 score cp 0 nodes 16917 nps 676680 tbhits 0 time 25 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 9 seldepth 14 multipv 1 score cp 0 nodes 26585 nps 699605 tbhits 0 time 38 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2c2
info depth 9 seldepth 9 multipv 2 score cp 0 nodes 26585 nps 699605 tbhits 0 time 38 pv d1d3 b1c3 c1d1 c8c2 e3e4 c2c1 d1d2 c1c2
info depth 10 seldepth 19 multipv 1 score cp 0 nodes 30331 nps 722166 tbhits 0 time 42 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2a2 e3e4 a2c2 c1d1 c2c1 d1d2 c1c2
info depth 10 seldepth 13 multipv 2 score cp 0 nodes 30331 nps 722166 tbhits 0 time 42 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2c1
info depth 11 seldepth 18 multipv 1 score cp 0 nodes 33124 nps 752818 tbhits 0 time 44 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2d2 e3e4 d2e2 e1d1 e2d2 d1c1 d2c2 c1d1
info depth 11 seldepth 9 multipv 2 score cp 0 nodes 33124 nps 752818 tbhits 0 time 44 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2c1
info depth 12 seldepth 16 multipv 1 score cp 0 nodes 35699 nps 776065 tbhits 0 time 46 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2d1 c1c2 d1c1
info depth 12 seldepth 14 multipv 2 score cp 0 nodes 35699 nps 776065 tbhits 0 time 46 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2c1 d2c2 c1d1 c2c1
info depth 13 seldepth 16 multipv 1 score cp 0 nodes 40371 nps 791588 tbhits 0 time 51 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2c2 c1d1 c2c1
info depth 13 seldepth 16 multipv 2 score cp 0 nodes 40371 nps 791588 tbhits 0 time 51 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2e1 d1c2 e1c1
info depth 14 seldepth 14 multipv 1 score cp 0 nodes 45634 nps 814892 tbhits 0 time 56 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2c2 c1d1
info depth 14 seldepth 13 multipv 2 score cp 0 nodes 45634 nps 814892 tbhits 0 time 56 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2e1 d1c2 e1c1
info depth 15 seldepth 14 multipv 1 score cp 0 nodes 52311 nps 843725 tbhits 0 time 62 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2c2 c1d1
info depth 15 seldepth 13 multipv 2 score cp 0 nodes 52311 nps 843725 tbhits 0 time 62 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2e1 d1c2 e1c1
info depth 16 seldepth 19 multipv 1 score cp 0 nodes 66357 nps 896716 tbhits 0 time 74 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1 c2c1
info depth 16 seldepth 13 multipv 2 score cp 0 nodes 66357 nps 896716 tbhits 0 time 74 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2e1 d1c2 e1c1
info depth 17 seldepth 14 multipv 1 score cp 0 nodes 84677 nps 1020204 tbhits 0 time 83 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1
info depth 17 seldepth 13 multipv 2 score cp 0 nodes 84677 nps 1020204 tbhits 0 time 83 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2e1 d1c2 e1c1
info depth 18 seldepth 17 multipv 1 score cp 0 nodes 101496 nps 1115340 tbhits 0 time 91 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1 c2d2 d1c1 d2d1
info depth 18 seldepth 14 multipv 2 score cp 0 nodes 101496 nps 1115340 tbhits 0 time 91 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2c2 c1d1
info depth 19 seldepth 16 multipv 1 score cp 0 nodes 126005 nps 1177616 tbhits 0 time 107 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1
info depth 19 seldepth 15 multipv 2 score cp 0 nodes 126005 nps 1177616 tbhits 0 time 107 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2d1 c1c2 d1d2
info depth 20 seldepth 31 multipv 1 score cp 0 nodes 165323 nps 1301755 tbhits 0 time 127 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1 c2c1
info depth 20 seldepth 15 multipv 2 score cp 0 nodes 165323 nps 1301755 tbhits 0 time 127 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2d1 c1c2 d1c1
info depth 21 seldepth 14 multipv 1 score cp 0 nodes 205145 nps 1290220 tbhits 0 time 159 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1
info depth 21 seldepth 14 multipv 2 score cp 0 nodes 205145 nps 1290220 tbhits 0 time 159 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2c2 c1d1
info depth 22 seldepth 14 multipv 1 score cp 0 nodes 257334 nps 1319661 tbhits 0 time 195 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1
info depth 22 seldepth 15 multipv 2 score cp 0 nodes 257334 nps 1319661 tbhits 0 time 195 pv d1d3 b1c3 c1d1 c8c1 d1d2 c1c2 d2e1 c2e2 e1d1 e2d2 d1c1 d2c2 c1d1 c2c1
info depth 23 seldepth 16 multipv 1 score cp 0 nodes 566199 nps 1415497 tbhits 0 time 400 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1 c2d2 d1c1
info depth 23 seldepth 46 multipv 2 score cp 0 nodes 566199 nps 1415497 tbhits 0 time 400 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 f8b4 a3b4 d1d2 c2c1 d2c2 c1d1 c2c1 d1d2 c1c2
info depth 24 seldepth 16 multipv 1 score cp 0 nodes 656932 nps 1431224 tbhits 0 time 459 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1
info depth 24 seldepth 20 multipv 2 score cp 0 nodes 656932 nps 1431224 tbhits 0 time 459 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 25 seldepth 16 multipv 1 score cp 0 nodes 779502 nps 1391967 tbhits 0 time 560 pv d1g1 b1c3 c1d1 c8c1 d1d2 c1d1 d2c2 d1d2 c2b1 d2b2 b1c1 b2c2 c1d1
info depth 25 seldepth 20 multipv 2 score cp 0 nodes 779502 nps 1391967 tbhits 0 time 560 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 b3b4 b1c1 c2b2 c1b1
info depth 26 seldepth 17 multipv 1 score cp 0 nodes 2694413 nps 1451731 hashfull 654 tbhits 0 time 1856 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 26 seldepth 25 multipv 2 score mate -10 nodes 2694413 nps 1451731 hashfull 654 tbhits 0 time 1856 pv d1g1 f8g7 c3c4 g7d4 g1d1 b1d2 c4c5 c8d8 b3b4 d8d3 a3a4 d3c3 c1b2 d2c4 b2a1 c3a3 a1b1 a3a1 b1c2 a1d1
info depth 27 seldepth 43 multipv 1 score cp 0 nodes 2965744 nps 1466737 hashfull 690 tbhits 0 time 2022 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 b3b4 b1c1 c2b2 c1c2 b2b1 c2c1
info depth 27 seldepth 21 multipv 2 score mate -10 nodes 2965744 nps 1466737 hashfull 690 tbhits 0 time 2022 pv d1g1 f8g7 c3c4 g7d4 g1d1 b1d2 c4c5 c8d8 b3b4 d8d3 a3a4 d3c3 c1b2 d2c4 b2a1 c3a3 a1b1 a3a1 b1c2 a1d1
info depth 28 seldepth 19 multipv 1 score cp 0 nodes 3170954 nps 1483140 hashfull 721 tbhits 0 time 2138 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 b3b4 b1c1 c2b2 c1c2 b2b1 c2c1
info depth 28 seldepth 21 multipv 2 score mate -10 nodes 3170954 nps 1483140 hashfull 721 tbhits 0 time 2138 pv d1g1 f8g7 c3c4 g7d4 g1d1 b1d2 c4c5 c8d8 b3b4 d8d3 a3a4 d3c3 c1b2 d2c4 b2a1 c3a3 a1b1 a3a1 b1c2 a1d1
info depth 29 seldepth 16 multipv 1 score cp 0 nodes 3597862 nps 1484879 hashfull 770 tbhits 0 time 2423 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1
info depth 29 seldepth 21 multipv 2 score mate -10 nodes 3597862 nps 1484879 hashfull 770 tbhits 0 time 2423 pv d1g1 f8g7 c3c4 g7d4 g1d1 b1d2 c4c5 c8d8 b3b4 d8d3 a3a4 d3c3 c1b2 d2c4 b2a1 c3a3 a1b1 a3a1 b1c2 a1d1
info depth 30 seldepth 41 multipv 1 score cp 0 nodes 3872681 nps 1480382 hashfull 801 tbhits 0 time 2616 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 b3b4 b1c1 c2b2 c1c2 b2b1 c2b2 b1c1 b2a2 f1f3 a2a1 c1c2 a1c1 c2b2 c1b1 b2c2 b1c1
info depth 29 seldepth 21 multipv 2 score mate -10 nodes 3872681 nps 1480382 hashfull 801 tbhits 0 time 2616 pv d1g1 f8g7 c3c4 g7d4 g1d1 b1d2 c4c5 c8d8 b3b4 d8d3 a3a4 d3c3 c1b2 d2c4 b2a1 c3a3 a1b1 a3a1 b1c2 a1d1
info depth 30 seldepth 41 multipv 1 score cp 0 nodes 4042543 nps 1465751 hashfull 816 tbhits 0 time 2758 pv d1f1 b1c3 c1d1 c8c1 d1d2 c1c2 d2d1 c2d2 d1c1 d2d1 c1c2 d1b1 b3b4 b1c1 c2b2 c1c2 b2b1 c2b2 b1c1 b2a2 f1f3 a2a1 c1c2 a1c1 c2b2 c1b1 b2c2 b1c1
info depth 30 seldepth 21 multipv 2 score mate -10 nodes 4042543 nps 1465751 hashfull 816 tbhits 0 time 2758 pv d1g1 f8g7 c3c4 g7d4 g1d1 b1d2 c4c5 c8d8 b3b4 d8d3 a3a4 d3c3 c1b2 d2c4 b2a1 c3a3 a1b1 a3a1 b1c2 a1d1
bestmove d1f1 ponder b1c3
```

**Comment by ddugovic** [comment] 2019-01-02 14:19
I wonder if king safety evaluation could be improved to better handle situations with sharply changing evaluations?  In particular there are several numbers here which are not variant-specific...

https://github.com/ddugovic/Stockfish/blob/b3316e8354c1c2c4b6e6639ff6e8e1eaf018d570/src/pawns.cpp#L481-L483

**Comment by ianfab** [comment] 2019-01-02 15:14
@ddugovic I would assume that the evaluation of pawn storms is very important in atomic chess, but I guess that the current array values are far from optimal. We used to have variant-specific values for it, but there have been multiple upstream changes to it in the meantime.

**Comment by ddugovic** [comment] 2019-01-02 15:37
That makes sense.  I suppose in hindsight I should have merged from upstream using a conditional which checks the variant (since the fallback behavior is to use `UnblockedStorm`.

I suppose I'll try 27e9128 first, and then reintroduce `UnblockedStorm` for variants if doing so gains Elo.

**Comment by ddugovic** [comment] 2019-01-07 05:30
Well, I tried some parameter tuning and not much happened.  Not sure where to go next.

**Comment by ddugovic** [comment] 2019-01-17 00:33
Hopefully the next [tuning session](http://35.161.250.236:6543/tests/view/5c3fccef6e23db07348e85c4) will result in meaningful parameter changes.  Else solving this issue might be infeasible...

**Comment by ddugovic** [comment] 2019-02-02 15:39
Maybe https://github.com/ddugovic/Stockfish/compare/f4729d2...da79222 isn't a true simplification although I don't see any Elo-gaining way to address this issue.

**Comment by ddugovic** [comment] 2019-02-23 00:44
While there is room for improvement in atomic chess evaluation/search, I can no longer reproduce the original problem.

**Closed by ddugovic** 2019-02-23 00:44 UTC
