### ISSUE TITLE
Regression tests also for SF standard

### ISSUE THREAD

**Issue by ppigazzini** [ddugovic/Stockfish#334] opened 2017-04-26 11:05 UTC
We routinely merge the upstream master, so IMO testing also SF standard can be helpful to view the net gain respect to the upstream patches.

**Comment by ianfab** [comment] 2017-04-26 11:36
What do you mean by "net gain respect to the upstream patches"?

**Comment by ppigazzini** [comment] 2017-04-26 11:59
If we merge a magical 100 ELO gain upstream patch, I'm expecting some gain in the variants. ATM it's easy because SF official has stalled, so the upstream contribution can be supposed null.

**Comment by ianfab** [comment] 2017-04-26 12:19
We have seen upstream patches in the range of 0-5 Elo that resulted in -50 or +50 Elo changes for some variants. For most variants there probably is a correlation with standard chess performance, but there always are a few upstream patches that would ruin variant performance over time if not fixed (e.g. the doubled pawn patch I intend to revert/adjust for horde chess because of http://35.161.250.236:6543/tests/view/58ff69856e23db04ee81d250), and a few patches that give a big gain in some variant, but only a very small gain in standard chess (e.g. some search changes that help a lot in crazyhouse).

So the problem is that the change in standard chess performance often is not a very good indicator for the change in variant performance.

**Comment by ppigazzini** [comment] 2017-04-26 12:52
Or we delete "standard" from the regression page, or we keep updated those data.

**Comment by ddugovic** [comment] 2017-04-26 13:00
To clarify by "the regression page" you mean this: http://35.161.250.236:6543/regression

**Comment by ppigazzini** [comment] 2017-04-26 13:08
yes (I'm working, sorry for the extreme synthesis)

**Comment by ianfab** [comment] 2017-04-26 13:08
Yes, it was inconsistent to start doing regression tests for standard chess and then discontinue.

Some time ago, bench was different from official stockfish, so we could not rely on measurements in official fishtest. Since the upstream changes to repetition detection, we have the same bench, so I no longer saw a reason to measure standard chess performance.

If you like, we can of course do short regression tests as for variants to roughly measure standard chess performance. The only thing I want to avoid is to use a lot of resources on huge standard chess tests that are not really our business.

**Comment by ppigazzini** [comment] 2017-04-26 13:35
I'm supporting the idea of doing regression tests for standard.
1. visual fast information about correlation degree between official SF and variants 
2. we have few workers and we test with only 2000 games: the degree of agreement between our standard tests and official SF test is an information about the quality of our framework.

**Comment by ianfab** [comment] 2017-04-26 13:44
If there are no objections, I will submit standard chess regression tests with low priority up to the latest version.

One more difference to official fishtest that might not be apparent is that I [adjusted adjudication conditions for cutechess](https://github.com/ianfab/fishtest/commit/5b0f1ea79571f0dbe78e718bf66029cf153dfb79), because variant SF might blunder away winning positions.

**Comment by ddugovic** [comment] 2017-04-26 14:12
Short regression tests for standard chess sound OK as long as we understand that upstream test results "trump" our results -- regression results are not for undoing upstream changes.

**Comment by ppigazzini** [comment] 2017-04-28 11:55
@ianfab @ddugovic  
1. good according with official regression tests, our (not so expensive) framework seems working fine despite the big error bars
  - Official +9.96 ELO from [31-12-16](http://tests.stockfishchess.org/tests/view/5867b55c0ebc5903140c639c) to [20-04-17](http://tests.stockfishchess.org/tests/view/58f92a310ebc59035df33d48)
  - Standard +6.95 ELO from 05-01-17 to 25-04-17
2. the variant more correlated with Standard had a healthy gain
  - King of the Hill +49.14 ELO from 05-01-17 to 25-04-17
3. the most popular Lichess variant simply skyrocketed
  - Crazy House +382.19 ELO  from 05-01-17 to 25-04-17

Great work Daniel and Fabian 👍

**Comment by ddugovic** [comment] 2017-04-28 12:55
1. To clarify (before someone asks again, I think it's been asked/suggested before), there's no "requirement" that changes merged from upstream must immediately result in any Elo gain in this repository.

**Closed** 2017-04-29 17:22 UTC
