### ISSUE TITLE
Three Check variant does not work correctly

### ISSUE THREAD

**Issue by KalenyUS** [ddugovic/Stockfish#160] opened 2016-12-07 07:50 UTC
With a depth of 10 the engine does not mind sacrifice to the queen in the three movement to give a stupid check.

Thanks.

**Comment by ianfab** [comment] 2016-12-07 10:59
Please provide the FEN of a position where this occurs so that we are able to reproduce it.

**Comment by ddugovic** [comment] 2016-12-07 13:57
Also, I'm not sure I understand the problem statement.  If the move wins (does it?), SF should play it even if it sacrifices a queen.

**Comment by KalenyUS** [comment] 2016-12-07 14:12
The movement does not win. Stockfish not performs the movement more precise, only seeks to sacrifice any piece with suck of give a check. 

Can you check this?

Ir occurs ni any position regardless of whether I open e4, d4, c4, etc...

**Comment by ianfab** [comment] 2016-12-07 14:40
@KalenyUS Well, we can not check this as long as we do not have a concrete position where Stockfish suggests a bad sacrifice as the best move. Please provide an [FEN](https://en.wikipedia.org/wiki/Forsyth%E2%80%93Edwards_Notation) or the exact line that leads to such a position. It would also be helpful to know whether you use it from the command line or otherwise which GUI you are using. Are you sure that the sacrifice does not lead to giving check three times (maybe later on in the variation after the sac) and hence winning the game? In [three-check chess](https://en.wikipedia.org/wiki/Three-check_chess) it is not uncommon to sacrifice a lot of material in order to win.

**Comment by KalenyUS** [comment] 2016-12-07 15:12
@ianfab Thanks for your response. 

I understand perfectly that Stockfish sacrifices any piece to give the third check, but is no the case. I repeat, althought having a depth of 10, Stockfish moves the pieces with a depth three...

It is not necessary to give the FEN because it works poorly in any position and situation of the game.

I have to say that I am using a custom GUI created by me. The program works very well in Standard Chess, Chess 960 but not in Three Check.  Obviously I change the configuration parameter of the engine to UCI_Variant=threecheck.

I am very grateful for the attention you are giving me.

**Comment by stockfishdeveloper** [comment] 2016-12-07 15:19
&KalenyUS You have been asked at least twice to give a specific FEN so that we can confirm or deny that there is a problem.
You have not done so and this can be closed as there is no issue here.
@ddugovic , @ianfab I suggest you close this

**Comment by KalenyUS** [comment] 2016-12-07 15:22
Now I do.

**Comment by KalenyUS** [comment] 2016-12-07 15:39
The console of my program when setting the parameter UCI_Variant = threecheck:

```
Stockfish 061216 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
id name Stockfish 061216 64
id author T. Romstad, M. Costalba, J. Kiiski, G. Linscott

option name Debug Log File type string default 
option name Contempt type spin default 0 min -100 max 100
option name Threads type spin default 1 min 1 max 128
option name Hash type spin default 16 min 1 max 1048576
option name Clear Hash type button
option name Ponder type check default false
option name MultiPV type spin default 1 min 1 max 500
option name Skill Level type spin default 20 min 0 max 20
option name Move Overhead type spin default 30 min 0 max 5000
option name Minimum Thinking Time type spin default 20 min 0 max 5000
option name Slow Mover type spin default 89 min 10 max 1000
option name nodestime type spin default 0 min 0 max 10000
option name UCI_Chess960 type check default false
option name UCI_Variant type combo default chess var chess var giveaway var atomic var crazyhouse var horde var kingofthehill var racingkings var threecheck
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 100
option name Syzygy50MoveRule type check default true
option name SyzygyProbeLimit type spin default 6 min 0 max 6
uciok
```
FEN of the position:

r1bqkb1r/ppp1pppp/2n2n2/3p4/Q7/2P2N2/PP1PPPPP/RNB1KB1R w KQkq - 3 4

The console of my program showing the movements:

```
Stockfish 061216 64 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
info string variant threecheck startpos rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 3+3 0 1
info depth 1 seldepth 1 multipv 1 score cp 54 nodes 22 nps 11000 tbhits 0 time 2 pv d2d4
info depth 2 seldepth 2 multipv 1 score cp 62 nodes 69 nps 34500 tbhits 0 time 2 pv d2d4 a7a6
info depth 3 seldepth 3 multipv 1 score cp 51 nodes 161 nps 80500 tbhits 0 time 2 pv c2c3 c7c6 d2d4
info depth 4 seldepth 4 multipv 1 score cp 11 nodes 461 nps 153666 tbhits 0 time 3 pv b1c3 e7e6 d2d4 b8c6
info depth 5 seldepth 5 multipv 1 score cp 94 nodes 883 nps 220750 tbhits 0 time 4 pv b1c3 c7c6 e2e3 a7a6 h2h4
info depth 6 seldepth 6 multipv 1 score cp 28 nodes 1917 nps 383400 tbhits 0 time 5 pv e2e3 c7c6 f1e2 h7h6 b1c3 e7e6
info depth 7 seldepth 7 multipv 1 score cp 59 nodes 2807 nps 467833 tbhits 0 time 6 pv e2e3 c7c6 f1e2 c8g4 e1g1 e7e6 b1c3
info depth 8 seldepth 8 multipv 1 score cp 57 nodes 4611 nps 658714 tbhits 0 time 7 pv e2e3 c7c6 f1e2 c8g4 b1c3 e7e6 h2h3 g4f3
info depth 9 seldepth 12 multipv 1 score cp 69 nodes 8922 nps 811090 tbhits 0 time 11 pv e2e3 c7c6 b1c3 d8d7 f1e2 h7h5 h2h3 e7e6 f3e5
info depth 10 seldepth 13 multipv 1 score cp 608 nodes 23618 nps 984083 tbhits 0 time 24 pv e2e3 c7c6 b1c3 d8d7 c3b5 c6b5 f3e5 g8h6 e5d7 c8d7 d1h5
bestmove e2e3 ponder c7c6
info depth 1 seldepth 1 multipv 1 score mate 1 nodes 23 nps 11500 tbhits 0 time 2 pv d1a4
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 46 nps 23000 tbhits 0 time 2 pv d1a4
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 69 nps 34500 tbhits 0 time 2 pv d1a4
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 92 nps 46000 tbhits 0 time 2 pv d1a4
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 115 nps 57500 tbhits 0 time 2 pv d1a4
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 138 nps 69000 tbhits 0 time 2 pv d1a4
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 161 nps 80500 tbhits 0 time 2 pv d1a4
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 184 nps 92000 tbhits 0 time 2 pv d1a4
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 207 nps 103500 tbhits 0 time 2 pv d1a4
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 230 nps 115000 tbhits 0 time 2 pv d1a4
bestmove d1a4
info depth 1 seldepth 2 multipv 1 score mate 1 nodes 36 nps 12000 tbhits 0 time 3 pv a4c6
info depth 2 seldepth 2 multipv 1 score mate 1 nodes 72 nps 24000 tbhits 0 time 3 pv a4c6
info depth 3 seldepth 2 multipv 1 score mate 1 nodes 108 nps 36000 tbhits 0 time 3 pv a4c6
info depth 4 seldepth 2 multipv 1 score mate 1 nodes 144 nps 48000 tbhits 0 time 3 pv a4c6
info depth 5 seldepth 2 multipv 1 score mate 1 nodes 180 nps 60000 tbhits 0 time 3 pv a4c6
info depth 6 seldepth 2 multipv 1 score mate 1 nodes 216 nps 54000 tbhits 0 time 4 pv a4c6
info depth 7 seldepth 2 multipv 1 score mate 1 nodes 252 nps 63000 tbhits 0 time 4 pv a4c6
info depth 8 seldepth 2 multipv 1 score mate 1 nodes 288 nps 72000 tbhits 0 time 4 pv a4c6
info depth 9 seldepth 2 multipv 1 score mate 1 nodes 324 nps 81000 tbhits 0 time 4 pv a4c6
info depth 10 seldepth 2 multipv 1 score mate 1 nodes 360 nps 90000 tbhits 0 time 4 pv a4c6
**bestmove a4c6**
```

Look at the last line -> Best move a4c6. Sacrifice the queen and it is an error in that position.

I apologize for the inconvenience.

**Comment by ianfab** [comment] 2016-12-07 15:40
@stockfishdeveloper I do not have the necessary rights to close issues in this repository. 

@KalenyUS You are using standard chess FEN for three-check chess, so it is not surprising at all that Stockfish is not working properly. This tells you why it is essential to give developers exact information on how to reproduce the issue.

**Comment by KalenyUS** [comment] 2016-12-07 15:49
But the position of the pieces is the same as in Standard Chess.  When changing the UCI configuration of the motor should it not be adapted?

Thanks again ianfab :)

**Comment by ianfab** [comment] 2016-12-07 16:00
Yes, the position of the pieces is the same, but the three-check FEN also has to encode the number of checks given by the two players. The correct FEN of the starting position is printed when setting the variant, and the FEN format is a [consensus with the developer of the WinBoard GUI](https://github.com/ddugovic/Stockfish/issues/61#issuecomment-249602516).

**Comment by ianfab** [comment] 2016-12-07 16:18
To solve it you have to use proper FENs. It is up to you to decide whether you implement this in your own GUI or use one that already supports it. But this is not an issue of Stockfish, so can close this.

**Comment by niklasf** [comment] 2016-12-07 16:19
(For example `r1bqkb1r/ppp1pppp/2n2n2/3p4/Q7/2P2N2/PP1PPPPP/RNB1KB1R w KQkq 3+3 - 3 4` because both sides have to give 3 more checks in order to win). Closing this now.

**Closed by niklasf** 2016-12-07 16:19 UTC

**Comment by ddugovic** [comment] 2016-12-07 17:52
Thanks @niklasf .

@KalenyUS With 17 open issues a SSCCE or at least a link to any lichess URL showing an example helps developers not go insane.  Thanks for providing the example.

**Comment by ddugovic** [comment] 2016-12-07 18:02
Also FYI for those on a Windows platform HGM has kindly released an alpha build of a WinBoard-AA GUI; I'll link to it when I have the time...
