### ISSUE TITLE
Antichess qsearch

### ISSUE THREAD

**Issue by ianfab** [ddugovic/Stockfish#70] opened 2016-10-18 17:26 UTC
If I am not mistaken, no qsearch is performed for antichess. Since there are no checks and since promotions are quiet moves in antichess, only captures are generated in qsearch. However, all captures have negative SEE (at least with the current SEE) due to negative piece values, so all captures are SEE pruned. This would mean that there no moves left to do a qsearch.

So what is qsearch supposed to do in antichess? I think it is difficult to determine which captures should be searched. Are there any rules of thumb which captures are good or bad in antichess?

**Comment by ddugovic** [comment] 2016-10-18 23:19
Good questions all around, and I don't know whether it makes sense for promotions to be quiet moves.  Sorry for dodging the negative SEE question; I'm unsure what search & evaluation changes make sense for antichess.

Captures and promotions which increase a player's overall mobility tend to be high-risk, high-reward.  It's possible to use Stockfish's `eval` command to dump the mobility score (from the current position).

Conversely, captures which take your opponent's most mobile ranged pieces (in the opening, bishops; in the endgame, rooks) generally make the game more difficult.

**Comment by stockfishdeveloper** [comment] 2016-10-19 15:03
I think qsearch is still needed with antichess.
When we cut off the main search, we don't want to find that one play later we are forced to make a capture.
So instead of pruning negative SEE values, prune the _positive_ ones.
That's as far as my thinking takes me.

**Comment by ianfab** [comment] 2016-10-19 16:42
The problem is that if there is a capture, all legal moves are captures due to the mandatory capture rule, so we either prune all or none of the captures (with the current SEE) if we only check the sign of the SEE value.

I think the first and most difficult step is to find a classifier that separates good and bad captures in antichess. How would you define SEE for antichess?

**Comment by ddugovic** [comment] 2016-10-19 17:12
The concept of SEE (let alone SEE search extension) seems alien to antichess as pruning captures seems to suffer to the horizon effect.  Some antichess engines use Proof-Number search to determine frontier nodes for extension.  I would be unsurprised if "prune none" is an improvement over "prune all".

I'm not opposed to changing the antichess piece constants to be positive (and making antichess material evaluation negate totals) since time and time again negative values seem to cause confusion.

**Comment by ianfab** [comment] 2016-10-19 17:25
A quick test on very short time controls indicates that it might indeed be better to prune none instead of all captures in qsearch: Total: 100 W: 42 L: 26 D: 32 ELO: 56.07 +-57.0 (95%) LOS: 97.6%

**Comment by stockfishdeveloper** [comment] 2016-10-19 21:13
What I'm trying to say is that in qsearch we look at all our _noncapture_  moves and if we reach a forced capture return the value of that piece based on its mobility. 
But I'm thinking that this would cause us to search a huge number of nodes in qsearch--there are usually many more "normal" moves than captures.
Maybe the engine would only search 5-10 "regular plies" and the rest is qsearch.
Would this work?

**Comment by ddugovic** [comment] 2016-10-19 22:25
Oh, right, a forcing move in antichess is one which hangs a piece or a series of pieces... I suppose a move (capture or non-capture) may be forcing if it forces the opponent to capture one or more pieces, for example:

`1.d3?? g5` is forcing on account of `2.Bxg5 Bg7 3.Bxe7 Bxb2 4.Bxd8 Bxa1 5.Bxc7 Bc3 6.Bxb8 Rxb8 7.Nxc3 d5 8.Nxd5 Nf6 9.Nxf6 Rg8 10.Nxe8 Rxg2 11.Bxg2 f6 12.Bxb7 Rxb7 13.Nxf6 h5 14.Nxh5 Rb1 15.Qxb1 Bb7 16.Qxb7 a6 17.Qxa6`

I'm unsure how best to test which moves are forcing.

**Comment by ianfab** [comment] 2016-10-20 08:02
This reminds me of an experiment with a "shortest series of captures" evaluation term I tried some time ago. Since it does some kind of search it is slow (there was a loop over all pieces using this function and it decreased nps by a factor of 3 in antichess), but it still was a slight improvement, so it contains some important imformation. It might be worth testing to use this information somewhere in the search instead of the evaluation function.

**Comment by ddugovic** [comment] 2016-10-20 10:57
If I remember correctly best results are had with Proof-Number search (PN^2) to identify frontier nodes, which obviously differs from how Stockfish searches:
https://chessprogramming.wikispaces.com/Proof-number+search

It's possible that Stockfish may require drastic changes to be able to play antichess well.  I'm unsure what to suggest since I need to be careful not to degrade performance for other variants.

**Comment by ianfab** [comment] 2016-10-20 14:51
It might well be that proof-number search is more suitable for antichess, but I think it should be possible to create a pretty strong antichess engine without completely changing stockfish's search.

**Comment by stockfishdeveloper** [comment] 2016-10-20 15:09
Has anyone successfully tried giving pieces negative values?

**Comment by ianfab** [comment] 2016-10-21 08:24
Do you mean in other antichess engines? I haven't looked much at the code of other antichess engines yet. The antichess piece values that are used in Stockfish can be found here: https://github.com/ddugovic/Stockfish/blob/master/src/types.h#L259-L264

**Comment by stockfishdeveloper** [comment] 2016-10-21 14:49
I would hazard a guess that the values of the pieces would have to fluctuate wildly over the course of the game.
Simply using middlegame and endgame values would not be enough.
I'm thinking more like having the values changes based on how active the game is, how much material left on the board, etc.
There's a lot of experimentation to be done in this regard though.

**Comment by ianfab** [comment] 2016-10-21 15:47
I agree that piece values are highly dependent on the position in antichess or rather that in contrast to standard chess there is no such obvious way of evaluating the position as the sum of piece values. Maybe we could include something like mobility into the calculation of the game phase to try to account for this. That would more or less do what you propose without having to change much code. The downside would be a less stable evaluation function.

**Comment by ddugovic** [comment] 2016-10-21 17:07
> I would hazard a guess that the values of the pieces would have to fluctuate wildly over the course of the game.

I'm not at all following this.  Note that even for concepts like "bishop pair" Stockfish does not change piece values but instead applies bonuses.  Stockfish even has mobility bonuses - check it out:

```
eval
      Eval term |    White    |    Black    |    Total
                |   MG    EG  |   MG    EG  |   MG    EG
----------------+-------------+-------------+-------------
       Material |   ---   --- |   ---   --- |  0.00  0.00
      Imbalance |   ---   --- |   ---   --- |  0.00  0.00
          Pawns |   ---   --- |   ---   --- |  0.00  0.00
        Knights |  0.13  0.00 |  0.13  0.00 |  0.00  0.00
         Bishop | -0.13 -0.39 | -0.13 -0.39 |  0.00  0.00
          Rooks | -0.28  0.00 | -0.28  0.00 |  0.00  0.00
         Queens |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
       Mobility | -0.76 -0.87 | -0.76 -0.87 |  0.00  0.00
    King safety |  0.97 -0.06 |  0.97 -0.06 |  0.00  0.00
        Threats |  0.00  0.10 |  0.00  0.10 |  0.00  0.00
   Passed pawns |  0.00  0.00 |  0.00  0.00 |  0.00  0.00
          Space |  0.46  0.00 |  0.46  0.00 |  0.00  0.00
----------------+-------------+-------------+-------------
          Total |   ---   --- |   ---   --- |  0.00  0.00

Total Evaluation: 0.08 (white side)
```

**Comment by stockfishdeveloper** [comment] 2016-10-21 20:36
@ddugovic 
I'm saying that we might have to adjust the piece values as the game goes on to make a stronger engine.
I'm sure bonuses and penalties will be needed as well.

**Comment by ddugovic** [comment] 2016-10-21 20:49
@stockfishdeveloper Piece values already adjust as the game progresses.  It's unprecedented for Stockfish to change the `Mg` and `Eg` constants at runtime.

I think we'd benefit from generating antichess Syzygybases; for atomic chess I've started such an effort at http://github.com/ddugovic/tb

**Comment by ddugovic** [comment] 2016-12-23 21:43
Last week using SPSA I inverted the giveaway piece values; now I am able to & will test and if successful commit (plus obvious CPP source file changes):

```
-  TempoMgAnti       = 0,     TempoEgAnti       = 0,
-  PawnValueMgAnti   = -137,  PawnValueEgAnti   = -360,
-  KnightValueMgAnti = -130,  KnightValueEgAnti = -41,
-  BishopValueMgAnti = -322,  BishopValueEgAnti = -64,
-  RookValueMgAnti   = -496,  RookValueEgAnti   =  62,
-  QueenValueMgAnti  = -187,  QueenValueEgAnti  = -318,
-  KingValueMgAnti   = -20,   KingValueEgAnti   =  130,
+  TempoMgAnti       = 0,    TempoEgAnti       = 0,
+  PawnValueMgAnti   = 137,  PawnValueEgAnti   = 332,
+  KnightValueMgAnti = 127,  KnightValueEgAnti = 41,
+  BishopValueMgAnti = 322,  BishopValueEgAnti = 64,
+  RookValueMgAnti   = 499,  RookValueEgAnti   = -63,
+  QueenValueMgAnti  = 186,  QueenValueEgAnti  = 322,
+  KingValueMgAnti   = 20,   KingValueEgAnti   = -131,
```

**Comment by lantonov** [comment] 2016-12-25 17:51
Some strategic advice in suicide which I read in finger notes in FICS:

"First,for beginners in suicide,here are the main rules(ask me for details or type help suicide):in suicide,the aim is to get rid of all your pieces,king included;this can seem pretty silly and easy,but IT IS NOT!The king does not play any special role,unlike classic chess;sothere is no check,no checkmate,no castling allowed.And of course , the fundamental rule is that capturing IS compulsory;anyway ,if you re in front of two or more possible captures,you may chose anyone.The final aim is to get rid of all pieces,or at least,to be in stalemate with less pieces than your oppoent!(of course,you can promote your pawns into anything,king too...)
 4: i completly agree with whiteknightmaster 's note 4
 5: If you read these rules,you may get a little bit confused,and the first suicide games you will have wont help you much;but i swear that after as less than 20 games,the tricky,strategic and tactical interest of suicide chess will blow you up!But hey! i love YOU ;-) So here are few strategic and tactic rules,just read it if you want,but its better having played a few antichess games before : 1 DO NOT give ,without any reason,your king!It is your best pieces,because of the"waiting moves"it can make;in the contrary,having more kings is a huge advantage. 2 DO NOT give too much pieces and pawns,unless you get a clear and quick victory ,or a decisive space advantage,or that you re clearly condemned to in order not to lose;this of course will look to you contrary to the aim of giving all your pieces,but the sense of this will appear when you ll get more experienced!
 6: 3 now a strategic advice;try to get the more space you can,so you may increase pressure on your opponent pieces(for ex rooks and  bishops),and get out of traps 4 try to get rid of your bishops and queen as soon as possible,because your opponent will try to take advantage of their great range to give all his material 5 and last(woooow! ) if you re in front of multiple available captures ,and for ex one of your opp's piece is protected and other(s) one(s) not,ALLWAYS (unless very particular positions...)capture the unprotected one;this will get clear when you ll play it,its because then your opponent as less choices remaining...
 7: still getting right into opening tricks;then go to this site,could help! http://catalin.francu.com/nilatac/book.php
 8: Here are a few interesting site related to suicide chess http://www.cs.unimaas.nl/icga/games/losingchess/start.html  http://www.pion.ch/Losing/ (in french,to translate it ,go to google)   http://www.matf.bg.ac.yu/~andrew/suicide/"

**Comment by ddugovic** [comment] 2016-12-25 17:54
That's not relevant to this issue (qsearch) and honestly I'm already aware of it, but thanks.

**Comment by lantonov** [comment] 2016-12-25 18:01
I was just trying to help and because there is no messaging board, I couldn't find better place to put it. But because you don't need it, I deleted it.

**Comment by ddugovic** [comment] 2016-12-25 18:31
No worries, I only criticized because I'm close to resolving qsearch.  Perhaps one of Lichess' [antichess forums](http://en.lichess.org/team/search?text=antichess) can suffice as a message board for discovering examples where either AI level 8 goes badly wrong, or analyses are incorrect.

(Unfortunately because "antichess" variants are weakly solved -- 1. e3 is a forced win -- I personally am not spending hours searching for good antichess examples.)

**Comment by ddugovic** [comment] 2016-12-26 12:21
I'm going to try re-tuning antichess piece values now.

**Comment by ianfab** [comment] 2016-12-26 13:07
Sorry if it is annoying, but I would like to insist on having positive test results for functional changes before merging them. As playing strength is increasing, it is getting more and more difficult to gain Elo and, at least in my experience, it is easy to lose a lot of Elo even by patches that look very sensible from a human's point of view.

By the way, I started several long tuning sessions, because I won't have access to my local and remote machines for the next few days. On the 31st, I will probably be able to post the regression test results for fishnet-231216 for all variants and hopefully also have some interesting tuning and test results.

**Comment by ddugovic** [comment] 2016-12-26 14:18
Thanks, I've been tuning & testing 24/7 (at 1+1, 10+1, 30+1, and 60+1) and every test result (even after a day of testing) is inconclusive (within the margin of error, certainly not regressing lots of Elo but possibly a slight regression).

Currently I am testing whether I can greatly improve over 758ef43bd4b051f8ac36a9da7604d03ee2d6ab1e.

**Comment by ddugovic** [comment] 2016-12-30 21:24
Okay, despite many tests improvements over the antichess code are elusive at this time.  I have closely examined the antichess evaluation code & although it is quite complex it seems that any possible simplification loses Elo, as does any other change I can imagine.

That said I will beautify some of that code, plus one slight simplification.

**Closed** 2016-12-30 22:44 UTC
