### ISSUE TITLE
fen where stockfish has trouble finding zh mate

### ISSUE THREAD

**Issue by isaacl** [ddugovic/Stockfish#148] opened 2016-12-02 02:05 UTC
```
setoption name UCI_Variant value crazyhouse
position fen r2q1rk1/pp2bb1p/2pp2pK/7N/3pPR1P/1B1P2p1/PPPq4/R7[PPBNNN] b - - 49 25
```

At low depths and move times it evals the position as completely lost with f7b3, at higher depth it finds an `#8` with Bxh4.

**Comment by ddugovic** [comment] 2016-12-02 06:19
Duplicated (that Stockfish discovers the mate around depth=17 time=30000 on my PC):

`info depth 17 seldepth 29 multipv 1 score mate 8 nodes 65299668 nps 1534404 hashfull 999 tbhits 0 time 42557 pv e7h4 b3f7 f8f7 N@f6 h4f6 N@e7 d8e7 h5f6 e7f6 N@e7 f6e7 B@f6 d2f4 f6g5 e7g5`

**Comment by stockfishdeveloper** [comment] 2016-12-02 06:50
Wow...it's incredible that Stockfish can see that given the nature of the position!

**Comment by ddugovic** [comment] 2016-12-02 07:12
It's funny that #95 improperly implemented could make it more difficult to solve positions like this one involving multiple quiet moves.

**Comment by sf-x** [comment] 2016-12-02 07:15
But it's not an issue. `f7b3` wins also (mate in 10 or 11 - not sure now).  Finding a longer but easier win first is normal.
> It's funny that #95 improperly implemented could make it more difficult to solve positions like this one involving multiple quiet moves.
Well, you know that Stockfish Matefinder is weaker. Why wouldn't matefinding hurt strength for crazyhouse as well?

**Comment by ddugovic** [comment] 2016-12-02 07:21
Good question, and we don't know the answer to that yet.  Maybe somehow crazyhouse chess is special and/or some aspects of what jhellis3 developed can be made useful in crazyhouse?

To be honest I was tempted to immediately close #95 but inevitably someone will open an issue just like it.

**Comment by sf-x** [comment] 2016-12-02 07:35
Note that the mate is only that long because of futile checks by white. When white runs out of checks and pieces in hand, he's mated in a few moves. If SF has to play that on board, it will find the mating moves. Before that, calculating the mate is a waste of time; confidence that it's there is enough. So I'd say that this is definitely a non-issue.

**Comment by sf-x** [comment] 2016-12-02 07:35
Unless you want a special matefinding mode.

**Comment by ddugovic** [comment] 2016-12-02 07:40
Oh, that's an interesting point: this position is not the best possible test position, since even if SF doesn't see the mate it can still manage to win (regardless of the evaluation).

Honestly a special matefinding mode could be interesting (and maybe I should maintain a mate_finder branch).

**Comment by Vinvin20** [comment] 2016-12-02 09:15
> Well, you know that Stockfish Matefinder is weaker. Why wouldn't matefinding hurt strength for crazyhouse as well?

Probably because of de nature of the game.
In chess, you've to play positionally, trying to improve your position and get a better position than your opponent then win a pawn (or more), then win the endgame with the small advantage.

Crazyhouse is way more tactical and mates in 20 can appears when both king are under heavy attack (a pawn or a piece more can be irrelevant) and finding the mate variation is the key to win the game.

**Comment by ddugovic** [comment] 2016-12-02 09:24
For what it's worth, I just created a [mate_finder](http://github.com/ddugovic/Stockfish/tree/mate_finder) branch.

**Comment by sf-x** [comment] 2016-12-02 12:09
> finding the mate variation is the key to win the game.

No. If you can GUESS which variation win or lose, you don't need to calculate. Example: If only check evasions you have just lose material for nothing, the position is in all likelihood lost. If remaining depth is low, it should just be considered lost without forther consideration.

**Comment by Vinvin20** [comment] 2016-12-02 13:05
Sometimes yes, sometimes no.

There's no doubt that SF-Matefinder is stronger than Regular-SF in tactical positions
Based on my test : http://www.talkchess.com/forum/viewtopic.php?p=673942#673942

> SF-MateFinder : found at least one time : 96 solutions ! 
> On 3 runs, Stockfish_160520_x64_modern_fast scored only 79 !

And crazyhouse is more tactical than chess !

**Comment by ianfab** [comment] 2016-12-02 13:10
@Vinvin20 You should not confuse finding the best move with playing strength. If you want to measure playing strength in tactical positions, you should play out these positions with the two version. The versions that has the better score can than be considered to be better in tactical positions. An engine does not necessarily have to find the best move as long as it finds a winning move.

**Comment by Vinvin20** [comment] 2016-12-02 13:14
It's a tactical set, so, no doubt the one who finds the solution will win the game.

**Comment by ianfab** [comment] 2016-12-02 13:23
Sorry, I haven't looked at the positions. If the positions are either completely won or lost depending on one move, you are right. However, I would be more interested in seeing results for positions where you have a winning combination, but if you do not see it the position still is about equal, because this is what usually is the case in real games and hence would in my opinion be a better indicator for playing strength.

**Comment by ddugovic** [comment] 2016-12-02 13:27
> It's a tactical set, so, no doubt the one who finds the solution will win the game.

That implies there is only one solution.  OTB it is common for a player to pass up a [mate in N](http://www.reddit.com/r/chess/comments/5cztbu/magnus_carlsen_just_missed_a_painfully_obvious/) yet play quite strongly.

**Comment by Vinvin20** [comment] 2016-12-02 13:28
In crazyhouse there's about no "equal positions".

**Comment by ianfab** [comment] 2016-12-02 13:55
Game theoretically it might well be that there are relatively few positions in crazyhouse that are a draw. However, we are so far away from perfect play in crazyhouse, that, in my opinion, it is pointless to talk about game theoretical values. Of course, there is no doubt that there is a lot of room for improvements on pruning, extensions, etc. in crazyhouse, but I am not entirely convinced that the methods of the matefinder are the right path for crazyhouse unless there are convincing test results.

**Comment by ddugovic** [comment] 2016-12-02 14:05
I too am deeply skeptical that the matefinder ideas will improve performance in anything other than extremely difficult puzzles involving quiet moves.  My [test results](http://github.com/ddugovic/Stockfish/issues/95#issuecomment-264448966) with [mate_finder](http://github.com/ddugovic/Stockfish/tree/mate_finder) show that it is slower.

**Comment by Vinvin20** [comment] 2016-12-02 14:13
I hope you are right ;-)

**Comment by isaacl** [comment] 2016-12-02 14:44
The reasons I posted this:
- stockfish's eval of f7b3 is higher than I've ever seen without a mate score. thought it was interesting.
- do we have different piece values for pieces in hand vs on board? Grabbing a pawn isn't exactly a quiet or necessarily bad move, pawn in hand is often better than bishop for attacks. surprised stockfish didn't explore the pawn line until depth 24.

**Comment by ianfab** [comment] 2016-12-02 14:52
@isaacl Yes, [pieces in hand have slightly different piece values](https://github.com/ddugovic/Stockfish/blob/caf7d91e9c0b07d70fe017860422ed48d618a860/src/psqt.cpp#L660-L662). However, your comment gave me the idea of evaluating pieces in hand based on the board position, e.g. adding a bonus for pawns in hand if there are empty squares on the 7th rank, if pieces in hand can be dropped with check, etc.

**Comment by sf-x** [comment] 2016-12-02 15:20
@ianfab Please to post your new code or description - I don't want to test conflicting changes.
> However, your comment gave me the idea of evaluating pieces in hand based on the board position, e.g. adding a bonus for pawns in hand if there are empty squares on the 7th rank, if pieces in hand can be dropped with check, etc.
Well, king safety evaluation in mainline Stockfish counts safe checks possible; but it ignores drops. Perharps accounting for drops but not otherwise changing the logic would be a good idea?

**Comment by ianfab** [comment] 2016-12-02 15:56
@sf-x I currently do not write or test any new code, because I am busy with creating a version of Stockfish that generates EPD opening books.

I had already tested this idea a few days ago, but it failed (I can search for the results later if you are interested), probably because it overvalues pieces in hand, since they usually have many possible checks. However, when I wrote it, I did not really think of extending this idea to other parts of the evaluation. It might be worth thinking about adding a function similar to `evaluate_pieces` for pieces in hand.

**Comment by sf-x** [comment] 2016-12-02 16:33
> I can search for the results later if you are interested

Yes please.
> probably because it overvalues pieces in hand, since they usually have many possible checks. 

Another possible reason is time control being too short to calculate out the attacks.

**Comment by ianfab** [comment] 2016-12-02 16:55
I have found the results:
```
LLR: -2.99 (-2.94,2.94) [0.00,20.00]
Total: 656 W: 292 L: 322 D: 42
```

**Comment by ddugovic** [comment] 2016-12-02 18:37
> Well, king safety evaluation in mainline Stockfish counts safe checks possible; but it ignores drops. Perhaps accounting for drops but not otherwise changing the logic would be a good idea?

Maybe penalize king safety based on drops on safe squares; for example in [this position](http://en.lichess.org/FbpWrfbW/black#43) at the end of a forcing variation, Black safely plays N@f3+ and White is hopelessly doomed.

Safe could mean any of:
* not attacked (by the defender)
* defended by a piece and only attacked by the defender's king
* perform a SEE evaluation

**Comment by ddugovic** [comment] 2016-12-03 02:56
Adding this mate in 15 puzzle here since #95 is resolved (I created a mate_finder branch):

```
setoption name UCI_Variant value crazyhouse
setoption name Threads value 4
position fen r5k1/pppqbrp1/2n3Bp/3p1n1p/4p3/1PN1P2B/P1PP2PP/R1B2RK1[NPq] b - - 33 17
go infinite
```

**Comment by jhellis3** [comment] 2016-12-03 18:12
Hi, just wanted to comment that at least one aspect of MF probably hurts much worse than normal in zh, and that is the TT changes. You only get 2/3rds the TT entries when using the full key, and due to zh having a naturally higher branching factor, there is probably much more hash pressure for any given depth.  If you have more hash than you can use in the average move time, the full keys can actually gain 1-2 Elo, but as soon as you get hash pressure, performance and Elo drops considerably. Not pruning in low material situations (in futility and null pruning) is also probably pretty useless in zh, since it is extremely unlikely for a pawn race to decide a zh game.

**Comment by ddugovic** [comment] 2016-12-06 10:29
Thanks @jhellis3 !  When reading the code I was thinking the same thing but merging the changes minus the TT changes seemed messy.  I figured I would merge all the changes and regression test before reverting anything or making more branches.

**Comment by Vinvin20** [comment] 2016-12-07 04:05
3 more games I found while browsing longest games from my recent match 1core vs 6cores. That confirms my thinking that SF should have a better mate finder algorithm : 

At moves 77 : https://fr.lichess.org/p36l0TmZ#154
Around move 65 : https://fr.lichess.org/rWTzvckw#129
Around move 66 : https://fr.lichess.org/v1SjNvzV#132

**Comment by ddugovic** [comment] 2016-12-08 02:53
Having the test positions is helpful.  Let's not jump to conclusions about whether the algorithm, parameters, or something else is the issue.

**Comment by Vinvin20** [comment] 2016-12-11 11:28
A condition like this one may help SF-zh in mating net : 
"No LMR if in danger of getting mated (like pruning)"
https://github.com/locutus2/Stockfish/compare/a47bbca...ba6bf2b

**Comment by ddugovic** [comment] 2016-12-11 12:32
Maybe.  Someone would need to test it following directions in #149.

**Comment by ianfab** [comment] 2016-12-11 12:41
The test is already running. So far the results are not very promising, but I will wait for the test to finish and then post the final results.

**Comment by ianfab** [comment] 2016-12-11 20:10
@Vinvin20 Here are the results for the patched you mentioned:
```
LLR: -3.06 (-2.94,2.94) [0.00,20.00]
Total: 1024 W: 483 L: 505 D: 36
```

**Comment by Vinvin20** [comment] 2016-12-11 22:08
Thanks for the test !
But disappointed by the results ...

**Comment by ddugovic** [comment] 2016-12-11 22:22
Severe changes (such as "always do X" or "never do X") tend to have severe effects.  The result is unfortunate but not surprising.

**Comment by Vinvin20** [comment] 2016-12-12 09:25
It's a severe change but for a small part of the three (where there is mates).

**Comment by jhellis3** [comment] 2016-12-13 19:44
I have found you don't really need to worry about LMR when it comes to seeing the actual mate.  Where LMR changes can make a difference is on the path towards the mate if that path involves sacrificing material.  The most significant mate detection change in MateFinder is the null move criteria alteration. I would suggest testing that alone; if any part of MateFinder may be beneficial to zh, I would expect that to be it.

**Comment by ddugovic** [comment] 2016-12-13 21:20
Thanks, I will test that alone now that I'm aware of what to isolate and test.

**Comment by ddugovic** [comment] 2016-12-18 20:01
Hm... I'm looking at http://github.com/jhellis3/Stockfish/blame/9914d9ccf7cb57b63c81d897334dae6a8178c6c5/src/search.cpp and a bit confused where the LMR change for "legal & available king moves check" is done.  Are we talking about [Step 8](http://github.com/official-stockfish/Stockfish/compare/master...jhellis3:mate_finder?expand=1#diff-71c8faa29f847041392f6e81e16bd9e6R751):

```
// Step 8. Null move search with verification search (is omitted in PV nodes)
```

**Comment by jhellis3** [comment] 2016-12-19 17:25
There is no LMR change I would recommend. The most valuable change is the condition in Step 8, for which you will also need the changes to movegen.h.

**Comment by ddugovic** [comment] 2016-12-21 11:51
Sadly Step 8 alone doesn't perform: `make profile-build` hangs.  On current master I tried simplifying this to see if I can get `make profile-build` to complete (although `make build` works, search produces no output):

```
    // Step 8. Null move search with verification search (is omitted in PV nodes)
#ifdef HORDE
    if (pos.is_horde()) {} else
#endif
    if (   !PvNode
        &&  eval >= beta
        && (ss->staticEval >= beta - 35 * (depth / ONE_PLY - 6) || depth >= 13 * ONE_PLY)
#ifdef CRAZYHOUSE
        &&  pos.is_house() ? (abs(eval) < 2 * VALUE_KNOWN_WIN
            && !(depth > 4 * ONE_PLY && (inCheck ? MoveList<LEGAL>(pos).size() < 6 : MoveList<LEGAL, KING>(pos).size() < 1))) :
            pos.non_pawn_material(pos.side_to_move()))
#else
        &&  pos.non_pawn_material(pos.side_to_move()))
#endif
    {
```

**Comment by ianfab** [comment] 2016-12-21 12:56
@ddugovic It probably fails because [`piece_on(from_sq(move))`](https://github.com/ddugovic/Stockfish/commit/5616e9e1235112fffefab9479c7b4345f5d3f686#diff-c725359b2d3e3728a3bf23db0b7ee870R62) does not work for piece drops.

**Comment by jhellis3** [comment] 2016-12-21 15:53
Why is inCheck ? there, that is not in my code?  I can't really comment on something which is not my code and where I can not see a diff.

**Comment by ddugovic** [comment] 2016-12-21 15:57
Thanks, that's much better.  I am now testing with:

```
    // Step 8. Null move search with verification search (is omitted in PV nodes)
#ifdef HORDE
    if (pos.is_horde()) {} else
#endif
    if (   !PvNode
        &&  eval >= beta
        && (ss->staticEval >= beta - 35 * (depth / ONE_PLY - 6) || depth >= 13 * ONE_PLY)
#ifdef CRAZYHOUSE
        && (pos.is_house() ? (eval < 2 * VALUE_KNOWN_WIN
            && !(depth > 4 * ONE_PLY && (MoveList<LEGAL, KING>(pos).size() < 1 && MoveList<LEGAL>(pos).size() < 6))) :
            pos.non_pawn_material(pos.side_to_move())))
#else
        &&  pos.non_pawn_material(pos.side_to_move()))
#endif
    {
```

**Comment by ddugovic** [comment] 2016-12-21 16:02
In desperation I added `inCheck` hoping that less code would be executed.

**Comment by ddugovic** [comment] 2016-12-22 18:19
Unfortunately this change does not scale.  Next I shall try replacing `MoveList<LEGAL, KING>(pos).size() < 1 || MoveList<LEGAL>(pos).size() < 6` with `MoveList<LEGAL, KING>(pos).size() < 1 || (inCheck && MoveList<LEGAL>(pos).size() < 6)` since some positions have over 100 legal moves and legal move generation is expensive:

```
==> test20161221-1.out <==
Score of PATCH vs Stockfish 211216 64 BMI2: 248 - 233 - 19  [0.515] 500
Elo difference: 10.43 +/- 29.91

==> test20161221-10.out <==
Score of PATCH vs Stockfish 211216 64 BMI2: 249 - 227 - 24  [0.522] 500
Elo difference: 15.30 +/- 29.77

==> test20161221-30.out <==
Score of PATCH vs Stockfish 211216 64 BMI2: 224 - 249 - 27  [0.475] 500
Elo difference: -17.39 +/- 29.68

==> test20161221-60.out <==
Score of PATCH vs Stockfish 211216 64 BMI2: 87 - 109 - 4  [0.445] 200
Elo difference: -38.37 +/- 48.20
```

**Comment by jhellis3** [comment] 2016-12-22 19:48
AFAIK, inCheck should always be false (due to step 5), so you are effectively removing the criteria, which can be reduced down to just MoveList<LEGAL, KING>(pos).size() < 1.

**Comment by ddugovic** [comment] 2016-12-22 21:06
Good observation & I'll try that instead.  (Also there's probably a more efficient way to check attacks any unoccupied squares which are not attacked!)

**Comment by ddugovic** [comment] 2016-12-23 22:13
In case this (admittedly delayed on my part as I resolve other issues) test fails, plan B is a @Vinvin20 [suggestion](http://github.com/ddugovic/Stockfish/issues/112#issuecomment-264409878):

> May be do null moves only when there's less than 3 pieces in (sum of both) hands. May be add a condition to be sure kings are safe.
> Null moves are interesting to find threats in still positions.

**Comment by Vinvin20** [comment] 2016-12-31 12:48
Nice to see there's progress here !
SF will be even stronger in opening with null-moves !

**Comment by ddugovic** [comment] 2016-12-31 17:08
Well... with #189 merged, this seems less necessary.  I'm going to try changing the rule from "no pieces in hand" to "under (depth - 4)/4 pieces in hand".

**Closed** 2016-12-31 21:26 UTC
